//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.25 at 04:16:47 PM GMT+02:00 
//


package za.co.bsv.bend.transformer.eft.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="installation-parameters" type="{}installationType"/>
 *         &lt;element name="user-parameters" type="{}userType"/>
 *         &lt;element name="transactions" type="{}transactionsType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "installationParameters",
    "userParameters",
    "transactions"
})
@XmlRootElement(name = "eft-file")
public class EftFile {

    @XmlElement(name = "installation-parameters", required = true)
    protected InstallationType installationParameters;
    @XmlElement(name = "user-parameters", required = true)
    protected UserType userParameters;
    @XmlElement(required = true)
    protected TransactionsType transactions;

    /**
     * Gets the value of the installationParameters property.
     * 
     * @return
     *     possible object is
     *     {@link InstallationType }
     *     
     */
    public InstallationType getInstallationParameters() {
        return installationParameters;
    }

    /**
     * Sets the value of the installationParameters property.
     * 
     * @param value
     *     allowed object is
     *     {@link InstallationType }
     *     
     */
    public void setInstallationParameters(InstallationType value) {
        this.installationParameters = value;
    }

    /**
     * Gets the value of the userParameters property.
     * 
     * @return
     *     possible object is
     *     {@link UserType }
     *     
     */
    public UserType getUserParameters() {
        return userParameters;
    }

    /**
     * Sets the value of the userParameters property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserType }
     *     
     */
    public void setUserParameters(UserType value) {
        this.userParameters = value;
    }

    /**
     * Gets the value of the transactions property.
     * 
     * @return
     *     possible object is
     *     {@link TransactionsType }
     *     
     */
    public TransactionsType getTransactions() {
        return transactions;
    }

    /**
     * Sets the value of the transactions property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransactionsType }
     *     
     */
    public void setTransactions(TransactionsType value) {
        this.transactions = value;
    }

}
