//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.25 at 04:16:47 PM GMT+02:00 
//


package za.co.bsv.bend.transformer.eft.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for transactionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="transactionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="type">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NCName">
 *               &lt;enumeration value="credit"/>
 *               &lt;enumeration value="debit"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="source-branch-code" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="source-account-number" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="destination-branch-code" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="destination-account-number" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="amount" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="user-reference" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="account-name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "transactionType", propOrder = {
    "type",
    "sourceBranchCode",
    "sourceAccountNumber",
    "destinationBranchCode",
    "destinationAccountNumber",
    "amount",
    "userReference",
    "accountName"
})
public class TransactionType {

    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String type;
    @XmlElement(name = "source-branch-code")
    protected int sourceBranchCode;
    @XmlElement(name = "source-account-number")
    protected long sourceAccountNumber;
    @XmlElement(name = "destination-branch-code")
    protected int destinationBranchCode;
    @XmlElement(name = "destination-account-number")
    protected long destinationAccountNumber;
    protected long amount;
    @XmlElement(name = "user-reference", required = true)
    protected String userReference;
    @XmlElement(name = "account-name", required = true)
    protected String accountName;

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the sourceBranchCode property.
     * 
     */
    public int getSourceBranchCode() {
        return sourceBranchCode;
    }

    /**
     * Sets the value of the sourceBranchCode property.
     * 
     */
    public void setSourceBranchCode(int value) {
        this.sourceBranchCode = value;
    }

    /**
     * Gets the value of the sourceAccountNumber property.
     * 
     */
    public long getSourceAccountNumber() {
        return sourceAccountNumber;
    }

    /**
     * Sets the value of the sourceAccountNumber property.
     * 
     */
    public void setSourceAccountNumber(long value) {
        this.sourceAccountNumber = value;
    }

    /**
     * Gets the value of the destinationBranchCode property.
     * 
     */
    public int getDestinationBranchCode() {
        return destinationBranchCode;
    }

    /**
     * Sets the value of the destinationBranchCode property.
     * 
     */
    public void setDestinationBranchCode(int value) {
        this.destinationBranchCode = value;
    }

    /**
     * Gets the value of the destinationAccountNumber property.
     * 
     */
    public long getDestinationAccountNumber() {
        return destinationAccountNumber;
    }

    /**
     * Sets the value of the destinationAccountNumber property.
     * 
     */
    public void setDestinationAccountNumber(long value) {
        this.destinationAccountNumber = value;
    }

    /**
     * Gets the value of the amount property.
     * 
     */
    public long getAmount() {
        return amount;
    }

    /**
     * Sets the value of the amount property.
     * 
     */
    public void setAmount(long value) {
        this.amount = value;
    }

    /**
     * Gets the value of the userReference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserReference() {
        return userReference;
    }

    /**
     * Sets the value of the userReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserReference(String value) {
        this.userReference = value;
    }

    /**
     * Gets the value of the accountName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountName() {
        return accountName;
    }

    /**
     * Sets the value of the accountName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountName(String value) {
        this.accountName = value;
    }

}
