//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.25 at 04:16:47 PM GMT+02:00 
//


package za.co.bsv.bend.transformer.eft.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for userType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="userType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="user-code" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="service-type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="short-name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="first-sequence-number" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="generation-number" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="source-account-name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "userType", propOrder = {
    "userCode",
    "serviceType",
    "shortName",
    "firstSequenceNumber",
    "generationNumber",
    "sourceAccountName"
})
public class UserType {

    @XmlElement(name = "user-code")
    protected int userCode;
    @XmlElement(name = "service-type", required = true)
    protected String serviceType;
    @XmlElement(name = "short-name", required = true)
    protected String shortName;
    @XmlElement(name = "first-sequence-number")
    protected int firstSequenceNumber;
    @XmlElement(name = "generation-number", required = true)
    protected String generationNumber;
    @XmlElement(name = "source-account-name", required = true)
    protected String sourceAccountName;

    /**
     * Gets the value of the userCode property.
     * 
     */
    public int getUserCode() {
        return userCode;
    }

    /**
     * Sets the value of the userCode property.
     * 
     */
    public void setUserCode(int value) {
        this.userCode = value;
    }

    /**
     * Gets the value of the serviceType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceType() {
        return serviceType;
    }

    /**
     * Sets the value of the serviceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceType(String value) {
        this.serviceType = value;
    }

    /**
     * Gets the value of the shortName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShortName() {
        return shortName;
    }

    /**
     * Sets the value of the shortName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShortName(String value) {
        this.shortName = value;
    }

    /**
     * Gets the value of the firstSequenceNumber property.
     * 
     */
    public int getFirstSequenceNumber() {
        return firstSequenceNumber;
    }

    /**
     * Sets the value of the firstSequenceNumber property.
     * 
     */
    public void setFirstSequenceNumber(int value) {
        this.firstSequenceNumber = value;
    }

    /**
     * Gets the value of the generationNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGenerationNumber() {
        return generationNumber;
    }

    /**
     * Sets the value of the generationNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGenerationNumber(String value) {
        this.generationNumber = value;
    }

    /**
     * Gets the value of the sourceAccountName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourceAccountName() {
        return sourceAccountName;
    }

    /**
     * Sets the value of the sourceAccountName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourceAccountName(String value) {
        this.sourceAccountName = value;
    }

}
