/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.bsva.dcms.commons.dto;
import java.io.Serializable;
import java.util.*;

public class CsfCashbackMccDTO implements Serializable
{
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/** 
	 * This attribute maps to the column CB_MCC in the CSF_CASHBACK_MCC table.
	 */
	protected int cbMcc;

	/**
	 * Method 'CsfCashbackMcc'
	 * 
	 */
	public CsfCashbackMccDTO()
	{
	}

	/**
	 * Method 'getCbMcc'
	 * 
	 * @return int
	 */
	public int getCbMcc()
	{
		return cbMcc;
	}

	/**
	 * Method 'setCbMcc'
	 * 
	 * @param cbMcc
	 */
	public void setCbMcc(int cbMcc)
	{
		this.cbMcc = cbMcc;
	}
}
