/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.bsva.dcms.commons.dto;

import java.io.Serializable;
import java.util.Date;
import java.math.BigDecimal;

public class CsfCompanyParametersDTO implements Serializable
{
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/** 
	 * This attribute maps to the column COMPANY_NAME in the CSF_COMPANY_PARAMETERS table.
	 */
	protected String companyName;

	/** 
	 * This attribute maps to the column COMPANY_NAME_ABREV in the CSF_COMPANY_PARAMETERS table.
	 */
	protected String companyNameAbrev;

	/** 
	 * This attribute maps to the column FULL_REPORT_NAME in the CSF_COMPANY_PARAMETERS table.
	 */
	protected String fullReportName;

	/** 
	 * This attribute maps to the column ADDRESS_1 in the CSF_COMPANY_PARAMETERS table.
	 */
	protected String address1;

	/** 
	 * This attribute maps to the column ADDRESS_2 in the CSF_COMPANY_PARAMETERS table.
	 */
	protected String address2;

	/** 
	 * This attribute maps to the column ADDRESS_3 in the CSF_COMPANY_PARAMETERS table.
	 */
	protected String address3;

	/** 
	 * This attribute maps to the column DIALLING_CODE in the CSF_COMPANY_PARAMETERS table.
	 */
	protected String diallingCode;

	/** 
	 * This attribute maps to the column TELEPHONE_NUMBER_1 in the CSF_COMPANY_PARAMETERS table.
	 */
	protected String telephoneNumber1;

	/** 
	 * This attribute maps to the column FAX_CODE in the CSF_COMPANY_PARAMETERS table.
	 */
	protected String faxCode;

	/** 
	 * This attribute maps to the column FAX_NUMBER in the CSF_COMPANY_PARAMETERS table.
	 */
	protected String faxNumber;

	/** 
	 * This attribute maps to the column EMAIL_ADDRESS in the CSF_COMPANY_PARAMETERS table.
	 */
	protected String emailAddress;

	/** 
	 * This attribute maps to the column REGISTRATION_NUMBER in the CSF_COMPANY_PARAMETERS table.
	 */
	protected String registrationNumber;

	/** 
	 * This attribute maps to the column VAT_NUMBER in the CSF_COMPANY_PARAMETERS table.
	 */
	protected String vatNumber;

	/** 
	 * This attribute maps to the column CONTACT_NAME in the CSF_COMPANY_PARAMETERS table.
	 */
	protected String contactName;

	/** 
	 * This attribute maps to the column INVOICE_NUMBER in the CSF_COMPANY_PARAMETERS table.
	 */
	protected int invoiceNumber;

	/** 
	 * This attribute represents whether the primitive attribute invoiceNumber is null.
	 */
	protected boolean invoiceNumberNull = true;

	/** 
	 * This attribute maps to the column INVOICE_DATE in the CSF_COMPANY_PARAMETERS table.
	 */
	protected Date invoiceDate;

	/** 
	 * This attribute maps to the column PREVIOUS_INVOICE_NUMBER in the CSF_COMPANY_PARAMETERS table.
	 */
	protected int previousInvoiceNumber;

	/** 
	 * This attribute represents whether the primitive attribute previousInvoiceNumber is null.
	 */
	protected boolean previousInvoiceNumberNull = true;

	/** 
	 * This attribute maps to the column VAT_PERCENT in the CSF_COMPANY_PARAMETERS table.
	 */
	protected int vatPercent;

	/** 
	 * This attribute maps to the column TEST_LIVE_INDICATOR in the CSF_COMPANY_PARAMETERS table.
	 */
	protected String testLiveIndicator;

	/** 
	 * This attribute maps to the column CREATED_BY in the CSF_COMPANY_PARAMETERS table.
	 */
	protected String createdBy;

	/** 
	 * This attribute maps to the column CREATED_DATE in the CSF_COMPANY_PARAMETERS table.
	 */
	protected Date createdDate;

	/** 
	 * This attribute maps to the column MODIFIED_BY in the CSF_COMPANY_PARAMETERS table.
	 */
	protected String modifiedBy;

	/** 
	 * This attribute maps to the column MODIFIED_DATE in the CSF_COMPANY_PARAMETERS table.
	 */
	protected Date modifiedDate;

	/** 
	 * This attribute maps to the column VALIDATION_CODE in the CSF_COMPANY_PARAMETERS table.
	 */
	protected String validationCode;

	/** 
	 * This attribute maps to the column INSTITUTION_CODE in the CSF_COMPANY_PARAMETERS table.
	 */
	protected String institutionCode;

	/** 
	 * This attribute maps to the column CURRENCY_CODE in the CSF_COMPANY_PARAMETERS table.
	 */
	protected String currencyCode;

	/** 
	 * This attribute maps to the column INPUT_RECORD_LENGTH in the CSF_COMPANY_PARAMETERS table.
	 */
	protected int inputRecordLength;

	/** 
	 * This attribute maps to the column INPUT_ID in the CSF_COMPANY_PARAMETERS table.
	 */
	protected String inputId;

	/** 
	 * This attribute maps to the column PREP_CODE in the CSF_COMPANY_PARAMETERS table.
	 */
	protected int prepCode;

	/** 
	 * This attribute represents whether the primitive attribute prepCode is null.
	 */
	protected boolean prepCodeNull = true;

	/** 
	 * This attribute maps to the column SEQ_NO in the CSF_COMPANY_PARAMETERS table.
	 */
	protected long seqNo;

	/** 
	 * This attribute represents whether the primitive attribute seqNo is null.
	 */
	protected boolean seqNoNull = true;

	/** 
	 * This attribute maps to the column CURRENCY_CODE_NUMBER in the CSF_COMPANY_PARAMETERS table.
	 */
	protected int currencyCodeNumber;

	/** 
	 * This attribute represents whether the primitive attribute currencyCodeNumber is null.
	 */
	protected boolean currencyCodeNumberNull = true;

	/** 
	 * This attribute maps to the column FLEET_TX_BIND_TIME in the CSF_COMPANY_PARAMETERS table.
	 */
	protected int fleetTxBindTime;

	/** 
	 * This attribute represents whether the primitive attribute fleetTxBindTime is null.
	 */
	protected boolean fleetTxBindTimeNull = true;

	/** 
	 * This attribute maps to the column TIERED_CUT_OFF in the CSF_COMPANY_PARAMETERS table.
	 */
	protected BigDecimal tieredCutOff;

	/**
	 * Method 'CsfCompanyParameters'
	 * 
	 */
	public CsfCompanyParametersDTO()
	{
	}

	/**
	 * Method 'getCompanyName'
	 * 
	 * @return String
	 */
	public String getCompanyName()
	{
		return companyName;
	}

	/**
	 * Method 'setCompanyName'
	 * 
	 * @param companyName
	 */
	public void setCompanyName(String companyName)
	{
		this.companyName = companyName;
	}

	/**
	 * Method 'getCompanyNameAbrev'
	 * 
	 * @return String
	 */
	public String getCompanyNameAbrev()
	{
		return companyNameAbrev;
	}

	/**
	 * Method 'setCompanyNameAbrev'
	 * 
	 * @param companyNameAbrev
	 */
	public void setCompanyNameAbrev(String companyNameAbrev)
	{
		this.companyNameAbrev = companyNameAbrev;
	}

	/**
	 * Method 'getFullReportName'
	 * 
	 * @return String
	 */
	public String getFullReportName()
	{
		return fullReportName;
	}

	/**
	 * Method 'setFullReportName'
	 * 
	 * @param fullReportName
	 */
	public void setFullReportName(String fullReportName)
	{
		this.fullReportName = fullReportName;
	}

	/**
	 * Method 'getAddress1'
	 * 
	 * @return String
	 */
	public String getAddress1()
	{
		return address1;
	}

	/**
	 * Method 'setAddress1'
	 * 
	 * @param address1
	 */
	public void setAddress1(String address1)
	{
		this.address1 = address1;
	}

	/**
	 * Method 'getAddress2'
	 * 
	 * @return String
	 */
	public String getAddress2()
	{
		return address2;
	}

	/**
	 * Method 'setAddress2'
	 * 
	 * @param address2
	 */
	public void setAddress2(String address2)
	{
		this.address2 = address2;
	}

	/**
	 * Method 'getAddress3'
	 * 
	 * @return String
	 */
	public String getAddress3()
	{
		return address3;
	}

	/**
	 * Method 'setAddress3'
	 * 
	 * @param address3
	 */
	public void setAddress3(String address3)
	{
		this.address3 = address3;
	}

	/**
	 * Method 'getDiallingCode'
	 * 
	 * @return String
	 */
	public String getDiallingCode()
	{
		return diallingCode;
	}

	/**
	 * Method 'setDiallingCode'
	 * 
	 * @param diallingCode
	 */
	public void setDiallingCode(String diallingCode)
	{
		this.diallingCode = diallingCode;
	}

	/**
	 * Method 'getTelephoneNumber1'
	 * 
	 * @return String
	 */
	public String getTelephoneNumber1()
	{
		return telephoneNumber1;
	}

	/**
	 * Method 'setTelephoneNumber1'
	 * 
	 * @param telephoneNumber1
	 */
	public void setTelephoneNumber1(String telephoneNumber1)
	{
		this.telephoneNumber1 = telephoneNumber1;
	}

	/**
	 * Method 'getFaxCode'
	 * 
	 * @return String
	 */
	public String getFaxCode()
	{
		return faxCode;
	}

	/**
	 * Method 'setFaxCode'
	 * 
	 * @param faxCode
	 */
	public void setFaxCode(String faxCode)
	{
		this.faxCode = faxCode;
	}

	/**
	 * Method 'getFaxNumber'
	 * 
	 * @return String
	 */
	public String getFaxNumber()
	{
		return faxNumber;
	}

	/**
	 * Method 'setFaxNumber'
	 * 
	 * @param faxNumber
	 */
	public void setFaxNumber(String faxNumber)
	{
		this.faxNumber = faxNumber;
	}

	/**
	 * Method 'getEmailAddress'
	 * 
	 * @return String
	 */
	public String getEmailAddress()
	{
		return emailAddress;
	}

	/**
	 * Method 'setEmailAddress'
	 * 
	 * @param emailAddress
	 */
	public void setEmailAddress(String emailAddress)
	{
		this.emailAddress = emailAddress;
	}

	/**
	 * Method 'getRegistrationNumber'
	 * 
	 * @return String
	 */
	public String getRegistrationNumber()
	{
		return registrationNumber;
	}

	/**
	 * Method 'setRegistrationNumber'
	 * 
	 * @param registrationNumber
	 */
	public void setRegistrationNumber(String registrationNumber)
	{
		this.registrationNumber = registrationNumber;
	}

	/**
	 * Method 'getVatNumber'
	 * 
	 * @return String
	 */
	public String getVatNumber()
	{
		return vatNumber;
	}

	/**
	 * Method 'setVatNumber'
	 * 
	 * @param vatNumber
	 */
	public void setVatNumber(String vatNumber)
	{
		this.vatNumber = vatNumber;
	}

	/**
	 * Method 'getContactName'
	 * 
	 * @return String
	 */
	public String getContactName()
	{
		return contactName;
	}

	/**
	 * Method 'setContactName'
	 * 
	 * @param contactName
	 */
	public void setContactName(String contactName)
	{
		this.contactName = contactName;
	}

	/**
	 * Method 'getInvoiceNumber'
	 * 
	 * @return int
	 */
	public int getInvoiceNumber()
	{
		return invoiceNumber;
	}

	/**
	 * Method 'setInvoiceNumber'
	 * 
	 * @param invoiceNumber
	 */
	public void setInvoiceNumber(int invoiceNumber)
	{
		this.invoiceNumber = invoiceNumber;
		this.invoiceNumberNull = false;
	}

	/**
	 * Method 'setInvoiceNumberNull'
	 * 
	 * @param value
	 */
	public void setInvoiceNumberNull(boolean value)
	{
		this.invoiceNumberNull = value;
	}

	/**
	 * Method 'isInvoiceNumberNull'
	 * 
	 * @return boolean
	 */
	public boolean isInvoiceNumberNull()
	{
		return invoiceNumberNull;
	}

	/**
	 * Method 'getInvoiceDate'
	 * 
	 * @return Date
	 */
	public Date getInvoiceDate()
	{
		return invoiceDate;
	}

	/**
	 * Method 'setInvoiceDate'
	 * 
	 * @param invoiceDate
	 */
	public void setInvoiceDate(Date invoiceDate)
	{
		this.invoiceDate = invoiceDate;
	}

	/**
	 * Method 'getPreviousInvoiceNumber'
	 * 
	 * @return int
	 */
	public int getPreviousInvoiceNumber()
	{
		return previousInvoiceNumber;
	}

	/**
	 * Method 'setPreviousInvoiceNumber'
	 * 
	 * @param previousInvoiceNumber
	 */
	public void setPreviousInvoiceNumber(int previousInvoiceNumber)
	{
		this.previousInvoiceNumber = previousInvoiceNumber;
		this.previousInvoiceNumberNull = false;
	}

	/**
	 * Method 'setPreviousInvoiceNumberNull'
	 * 
	 * @param value
	 */
	public void setPreviousInvoiceNumberNull(boolean value)
	{
		this.previousInvoiceNumberNull = value;
	}

	/**
	 * Method 'isPreviousInvoiceNumberNull'
	 * 
	 * @return boolean
	 */
	public boolean isPreviousInvoiceNumberNull()
	{
		return previousInvoiceNumberNull;
	}

	/**
	 * Method 'getVatPercent'
	 * 
	 * @return int
	 */
	public int getVatPercent()
	{
		return vatPercent;
	}

	/**
	 * Method 'setVatPercent'
	 * 
	 * @param vatPercent
	 */
	public void setVatPercent(int vatPercent)
	{
		this.vatPercent = vatPercent;
	}

	/**
	 * Method 'getTestLiveIndicator'
	 * 
	 * @return String
	 */
	public String getTestLiveIndicator()
	{
		return testLiveIndicator;
	}

	/**
	 * Method 'setTestLiveIndicator'
	 * 
	 * @param testLiveIndicator
	 */
	public void setTestLiveIndicator(String testLiveIndicator)
	{
		this.testLiveIndicator = testLiveIndicator;
	}

	/**
	 * Method 'getCreatedBy'
	 * 
	 * @return String
	 */
	public String getCreatedBy()
	{
		return createdBy;
	}

	/**
	 * Method 'setCreatedBy'
	 * 
	 * @param createdBy
	 */
	public void setCreatedBy(String createdBy)
	{
		this.createdBy = createdBy;
	}

	/**
	 * Method 'getCreatedDate'
	 * 
	 * @return Date
	 */
	public Date getCreatedDate()
	{
		return createdDate;
	}

	/**
	 * Method 'setCreatedDate'
	 * 
	 * @param createdDate
	 */
	public void setCreatedDate(Date createdDate)
	{
		this.createdDate = createdDate;
	}

	/**
	 * Method 'getModifiedBy'
	 * 
	 * @return String
	 */
	public String getModifiedBy()
	{
		return modifiedBy;
	}

	/**
	 * Method 'setModifiedBy'
	 * 
	 * @param modifiedBy
	 */
	public void setModifiedBy(String modifiedBy)
	{
		this.modifiedBy = modifiedBy;
	}

	/**
	 * Method 'getModifiedDate'
	 * 
	 * @return Date
	 */
	public Date getModifiedDate()
	{
		return modifiedDate;
	}

	/**
	 * Method 'setModifiedDate'
	 * 
	 * @param modifiedDate
	 */
	public void setModifiedDate(Date modifiedDate)
	{
		this.modifiedDate = modifiedDate;
	}

	/**
	 * Method 'getValidationCode'
	 * 
	 * @return String
	 */
	public String getValidationCode()
	{
		return validationCode;
	}

	/**
	 * Method 'setValidationCode'
	 * 
	 * @param validationCode
	 */
	public void setValidationCode(String validationCode)
	{
		this.validationCode = validationCode;
	}

	/**
	 * Method 'getInstitutionCode'
	 * 
	 * @return String
	 */
	public String getInstitutionCode()
	{
		return institutionCode;
	}

	/**
	 * Method 'setInstitutionCode'
	 * 
	 * @param institutionCode
	 */
	public void setInstitutionCode(String institutionCode)
	{
		this.institutionCode = institutionCode;
	}

	/**
	 * Method 'getCurrencyCode'
	 * 
	 * @return String
	 */
	public String getCurrencyCode()
	{
		return currencyCode;
	}

	/**
	 * Method 'setCurrencyCode'
	 * 
	 * @param currencyCode
	 */
	public void setCurrencyCode(String currencyCode)
	{
		this.currencyCode = currencyCode;
	}

	/**
	 * Method 'getInputRecordLength'
	 * 
	 * @return int
	 */
	public int getInputRecordLength()
	{
		return inputRecordLength;
	}

	/**
	 * Method 'setInputRecordLength'
	 * 
	 * @param inputRecordLength
	 */
	public void setInputRecordLength(int inputRecordLength)
	{
		this.inputRecordLength = inputRecordLength;
	}

	/**
	 * Method 'getInputId'
	 * 
	 * @return String
	 */
	public String getInputId()
	{
		return inputId;
	}

	/**
	 * Method 'setInputId'
	 * 
	 * @param inputId
	 */
	public void setInputId(String inputId)
	{
		this.inputId = inputId;
	}

	/**
	 * Method 'getPrepCode'
	 * 
	 * @return int
	 */
	public int getPrepCode()
	{
		return prepCode;
	}

	/**
	 * Method 'setPrepCode'
	 * 
	 * @param prepCode
	 */
	public void setPrepCode(int prepCode)
	{
		this.prepCode = prepCode;
		this.prepCodeNull = false;
	}

	/**
	 * Method 'setPrepCodeNull'
	 * 
	 * @param value
	 */
	public void setPrepCodeNull(boolean value)
	{
		this.prepCodeNull = value;
	}

	/**
	 * Method 'isPrepCodeNull'
	 * 
	 * @return boolean
	 */
	public boolean isPrepCodeNull()
	{
		return prepCodeNull;
	}

	/**
	 * Method 'getSeqNo'
	 * 
	 * @return long
	 */
	public long getSeqNo()
	{
		return seqNo;
	}

	/**
	 * Method 'setSeqNo'
	 * 
	 * @param seqNo
	 */
	public void setSeqNo(long seqNo)
	{
		this.seqNo = seqNo;
		this.seqNoNull = false;
	}

	/**
	 * Method 'setSeqNoNull'
	 * 
	 * @param value
	 */
	public void setSeqNoNull(boolean value)
	{
		this.seqNoNull = value;
	}

	/**
	 * Method 'isSeqNoNull'
	 * 
	 * @return boolean
	 */
	public boolean isSeqNoNull()
	{
		return seqNoNull;
	}

	/**
	 * Method 'getCurrencyCodeNumber'
	 * 
	 * @return int
	 */
	public int getCurrencyCodeNumber()
	{
		return currencyCodeNumber;
	}

	/**
	 * Method 'setCurrencyCodeNumber'
	 * 
	 * @param currencyCodeNumber
	 */
	public void setCurrencyCodeNumber(int currencyCodeNumber)
	{
		this.currencyCodeNumber = currencyCodeNumber;
		this.currencyCodeNumberNull = false;
	}

	/**
	 * Method 'setCurrencyCodeNumberNull'
	 * 
	 * @param value
	 */
	public void setCurrencyCodeNumberNull(boolean value)
	{
		this.currencyCodeNumberNull = value;
	}

	/**
	 * Method 'isCurrencyCodeNumberNull'
	 * 
	 * @return boolean
	 */
	public boolean isCurrencyCodeNumberNull()
	{
		return currencyCodeNumberNull;
	}

	/**
	 * Method 'getFleetTxBindTime'
	 * 
	 * @return int
	 */
	public int getFleetTxBindTime()
	{
		return fleetTxBindTime;
	}

	/**
	 * Method 'setFleetTxBindTime'
	 * 
	 * @param fleetTxBindTime
	 */
	public void setFleetTxBindTime(int fleetTxBindTime)
	{
		this.fleetTxBindTime = fleetTxBindTime;
		this.fleetTxBindTimeNull = false;
	}

	/**
	 * Method 'setFleetTxBindTimeNull'
	 * 
	 * @param value
	 */
	public void setFleetTxBindTimeNull(boolean value)
	{
		this.fleetTxBindTimeNull = value;
	}

	/**
	 * Method 'isFleetTxBindTimeNull'
	 * 
	 * @return boolean
	 */
	public boolean isFleetTxBindTimeNull()
	{
		return fleetTxBindTimeNull;
	}

	/**
	 * Method 'getTieredCutOff'
	 * 
	 * @return BigDecimal
	 */
	public BigDecimal getTieredCutOff()
	{
		return tieredCutOff;
	}

	/**
	 * Method 'setTieredCutOff'
	 * 
	 * @param tieredCutOff
	 */
	public void setTieredCutOff(BigDecimal tieredCutOff)
	{
		this.tieredCutOff = tieredCutOff;
	}
}
