/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.bsva.dcms.commons.dto;


import java.io.Serializable;
import java.util.*;
import java.util.Date;

public class CsfDeliveryServicesDTO implements Serializable
{
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/** 
	 * This attribute maps to the column FILENAME_PREFIX in the CSF_DELIVERY_SERVICES table.
	 */
	protected String filenamePrefix;

	/** 
	 * This attribute maps to the column MEDIA_TYPE in the CSF_DELIVERY_SERVICES table.
	 */
	protected String mediaType;

	/** 
	 * This attribute maps to the column INWARD_OUTWARD_IND in the CSF_DELIVERY_SERVICES table.
	 */
	protected String inwardOutwardInd;

	/** 
	 * This attribute maps to the column DESCRIPTION in the CSF_DELIVERY_SERVICES table.
	 */
	protected String description;

	/** 
	 * This attribute maps to the column SERVICE in the CSF_DELIVERY_SERVICES table.
	 */
	protected String service;

	/** 
	 * This attribute maps to the column SUB_SERVICE in the CSF_DELIVERY_SERVICES table.
	 */
	protected String subService;

	/** 
	 * This attribute maps to the column FORMAT in the CSF_DELIVERY_SERVICES table.
	 */
	protected String format;

	/** 
	 * This attribute maps to the column DESTINATION_CODE in the CSF_DELIVERY_SERVICES table.
	 */
	protected int destinationCode;

	/** 
	 * This attribute maps to the column BACKUP_FORMAT in the CSF_DELIVERY_SERVICES table.
	 */
	protected String backupFormat;

	/** 
	 * This attribute maps to the column ACTIVE_INDICATOR in the CSF_DELIVERY_SERVICES table.
	 */
	protected String activeIndicator;

	/** 
	 * This attribute maps to the column CREATED_BY in the CSF_DELIVERY_SERVICES table.
	 */
	protected String createdBy;

	/** 
	 * This attribute maps to the column CREATED_DATE in the CSF_DELIVERY_SERVICES table.
	 */
	protected Date createdDate;

	/** 
	 * This attribute maps to the column MODIFIED_BY in the CSF_DELIVERY_SERVICES table.
	 */
	protected String modifiedBy;

	/** 
	 * This attribute maps to the column MODIFIED_DATE in the CSF_DELIVERY_SERVICES table.
	 */
	protected Date modifiedDate;

	/** 
	 * This attribute maps to the column HEADER_REFERENCE in the CSF_DELIVERY_SERVICES table.
	 */
	protected String headerReference;

	/** 
	 * This attribute maps to the column FILE_FORMAT in the CSF_DELIVERY_SERVICES table.
	 */
	protected String fileFormat;
	
	protected int id;


	/**
	 * Method 'CsfDeliveryServices'
	 * 
	 */
	public CsfDeliveryServicesDTO()
	{
	}

	/**
	 * Method 'getFilenamePrefix'
	 * 
	 * @return String
	 */
	public String getFilenamePrefix()
	{
		return filenamePrefix;
	}

	/**
	 * Method 'setFilenamePrefix'
	 * 
	 * @param filenamePrefix
	 */
	public void setFilenamePrefix(String filenamePrefix)
	{
		this.filenamePrefix = filenamePrefix;
	}

	/**
	 * Method 'getMediaType'
	 * 
	 * @return String
	 */
	public String getMediaType()
	{
		return mediaType;
	}

	/**
	 * Method 'setMediaType'
	 * 
	 * @param mediaType
	 */
	public void setMediaType(String mediaType)
	{
		this.mediaType = mediaType;
	}

	/**
	 * Method 'getInwardOutwardInd'
	 * 
	 * @return String
	 */
	public String getInwardOutwardInd()
	{
		return inwardOutwardInd;
	}

	/**
	 * Method 'setInwardOutwardInd'
	 * 
	 * @param inwardOutwardInd
	 */
	public void setInwardOutwardInd(String inwardOutwardInd)
	{
		this.inwardOutwardInd = inwardOutwardInd;
	}

	/**
	 * Method 'getDescription'
	 * 
	 * @return String
	 */
	public String getDescription()
	{
		return description;
	}

	/**
	 * Method 'setDescription'
	 * 
	 * @param description
	 */
	public void setDescription(String description)
	{
		this.description = description;
	}

	/**
	 * Method 'getService'
	 * 
	 * @return String
	 */
	public String getService()
	{
		return service;
	}

	/**
	 * Method 'setService'
	 * 
	 * @param service
	 */
	public void setService(String service)
	{
		this.service = service;
	}

	/**
	 * Method 'getSubService'
	 * 
	 * @return String
	 */
	public String getSubService()
	{
		return subService;
	}

	/**
	 * Method 'setSubService'
	 * 
	 * @param subService
	 */
	public void setSubService(String subService)
	{
		this.subService = subService;
	}

	/**
	 * Method 'getFormat'
	 * 
	 * @return String
	 */
	public String getFormat()
	{
		return format;
	}

	/**
	 * Method 'setFormat'
	 * 
	 * @param format
	 */
	public void setFormat(String format)
	{
		this.format = format;
	}

	/**
	 * Method 'getDestinationCode'
	 * 
	 * @return int
	 */
	public int getDestinationCode()
	{
		return destinationCode;
	}

	/**
	 * Method 'setDestinationCode'
	 * 
	 * @param destinationCode
	 */
	public void setDestinationCode(int destinationCode)
	{
		this.destinationCode = destinationCode;
	}

	/**
	 * Method 'getBackupFormat'
	 * 
	 * @return String
	 */
	public String getBackupFormat()
	{
		return backupFormat;
	}

	/**
	 * Method 'setBackupFormat'
	 * 
	 * @param backupFormat
	 */
	public void setBackupFormat(String backupFormat)
	{
		this.backupFormat = backupFormat;
	}

	/**
	 * Method 'getActiveIndicator'
	 * 
	 * @return String
	 */
	public String getActiveIndicator()
	{
		return activeIndicator;
	}

	/**
	 * Method 'setActiveIndicator'
	 * 
	 * @param activeIndicator
	 */
	public void setActiveIndicator(String activeIndicator)
	{
		this.activeIndicator = activeIndicator;
	}

	/**
	 * Method 'getCreatedBy'
	 * 
	 * @return String
	 */
	public String getCreatedBy()
	{
		return createdBy;
	}

	/**
	 * Method 'setCreatedBy'
	 * 
	 * @param createdBy
	 */
	public void setCreatedBy(String createdBy)
	{
		this.createdBy = createdBy;
	}

	/**
	 * Method 'getCreatedDate'
	 * 
	 * @return Date
	 */
	public Date getCreatedDate()
	{
		return createdDate;
	}

	/**
	 * Method 'setCreatedDate'
	 * 
	 * @param createdDate
	 */
	public void setCreatedDate(Date createdDate)
	{
		this.createdDate = createdDate;
	}

	/**
	 * Method 'getModifiedBy'
	 * 
	 * @return String
	 */
	public String getModifiedBy()
	{
		return modifiedBy;
	}

	/**
	 * Method 'setModifiedBy'
	 * 
	 * @param modifiedBy
	 */
	public void setModifiedBy(String modifiedBy)
	{
		this.modifiedBy = modifiedBy;
	}

	/**
	 * Method 'getModifiedDate'
	 * 
	 * @return Date
	 */
	public Date getModifiedDate()
	{
		return modifiedDate;
	}

	/**
	 * Method 'setModifiedDate'
	 * 
	 * @param modifiedDate
	 */
	public void setModifiedDate(Date modifiedDate)
	{
		this.modifiedDate = modifiedDate;
	}

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	/**
	 * Method 'getHeaderReference'
	 * 
	 * @return String
	 */
	public String getHeaderReference()
	{
		return headerReference;
	}

	/**
	 * Method 'setHeaderReference'
	 * 
	 * @param headerReference
	 */
	public void setHeaderReference(String headerReference)
	{
		this.headerReference = headerReference;
	}

	/**
	 * Method 'getFileFormat'
	 * 
	 * @return String
	 */
	public String getFileFormat()
	{
		return fileFormat;
	}

	/**
	 * Method 'setFileFormat'
	 * 
	 * @param fileFormat
	 */
	public void setFileFormat(String fileFormat)
	{
		this.fileFormat = fileFormat;
	}
}
