/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */
package com.bsva.dcms.commons.dto;

import java.io.Serializable;


public class CsfDirectoriesDTO implements Serializable
{
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/** 
	 * This attribute maps to the column DIRECTORY_NAME in the CSF_DIRECTORIES table.
	 */
	protected String directoryName;

	/** 
	 * This attribute maps to the column DIRECTORY_PATH in the CSF_DIRECTORIES table.
	 */
	protected String directoryPath;

	/**
	 * Method 'CsfDirectories'
	 * 
	 */
	public CsfDirectoriesDTO()
	{
	}

	/**
	 * Method 'getDirectoryName'
	 * 
	 * @return String
	 */
	public String getDirectoryName()
	{
		return directoryName;
	}

	/**
	 * Method 'setDirectoryName'
	 * 
	 * @param directoryName
	 */
	public void setDirectoryName(String directoryName)
	{
		this.directoryName = directoryName;
	}

	/**
	 * Method 'getDirectoryPath'
	 * 
	 * @return String
	 */
	public String getDirectoryPath()
	{
		return directoryPath;
	}

	/**
	 * Method 'setDirectoryPath'
	 * 
	 * @param directoryPath
	 */
	public void setDirectoryPath(String directoryPath)
	{
		this.directoryPath = directoryPath;
	}

}
