/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.bsva.dcms.commons.dto;


import java.io.Serializable;
import java.util.*;

public class CsfErrorCodesDTO implements Serializable
{
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/** 
	 * This attribute maps to the column ERROR_CODE in the CSF_ERROR_CODES table.
	 */
	protected int errorCode;

	/** 
	 * This attribute maps to the column ERROR_MESSAGE in the CSF_ERROR_CODES table.
	 */
	protected String errorMessage;

	/** 
	 * This attribute maps to the column ERROR_REJECT_LEVEL in the CSF_ERROR_CODES table.
	 */
	protected String errorRejectLevel;

	/**
	 * Method 'CsfErrorCodes'
	 * 
	 */
	public CsfErrorCodesDTO()
	{
	}

	/**
	 * Method 'getErrorCode'
	 * 
	 * @return int
	 */
	public int getErrorCode()
	{
		return errorCode;
	}

	/**
	 * Method 'setErrorCode'
	 * 
	 * @param errorCode
	 */
	public void setErrorCode(int errorCode)
	{
		this.errorCode = errorCode;
	}

	/**
	 * Method 'getErrorMessage'
	 * 
	 * @return String
	 */
	public String getErrorMessage()
	{
		return errorMessage;
	}

	/**
	 * Method 'setErrorMessage'
	 * 
	 * @param errorMessage
	 */
	public void setErrorMessage(String errorMessage)
	{
		this.errorMessage = errorMessage;
	}

	/**
	 * Method 'getErrorRejectLevel'
	 * 
	 * @return String
	 */
	public String getErrorRejectLevel()
	{
		return errorRejectLevel;
	}

	/**
	 * Method 'setErrorRejectLevel'
	 * 
	 * @param errorRejectLevel
	 */
	public void setErrorRejectLevel(String errorRejectLevel)
	{
		this.errorRejectLevel = errorRejectLevel;
	}

}
