/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.bsva.dcms.commons.dto;

import java.io.Serializable;
import java.util.*;

public class CsfFilenameLookupDTO implements Serializable
{
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/** 
	 * This attribute maps to the column NUM_INDEX in the CSF_FILENAME_LOOKUP table.
	 */
	protected int numIndex;

	/** 
	 * This attribute maps to the column ALPHA_SEQ in the CSF_FILENAME_LOOKUP table.
	 */
	protected String alphaSeq;

	/**
	 * Method 'CsfFilenameLookup'
	 * 
	 */
	public CsfFilenameLookupDTO()
	{
	}

	/**
	 * Method 'getNumIndex'
	 * 
	 * @return int
	 */
	public int getNumIndex()
	{
		return numIndex;
	}

	/**
	 * Method 'setNumIndex'
	 * 
	 * @param numIndex
	 */
	public void setNumIndex(int numIndex)
	{
		this.numIndex = numIndex;
	}

	/**
	 * Method 'getAlphaSeq'
	 * 
	 * @return String
	 */
	public String getAlphaSeq()
	{
		return alphaSeq;
	}

	/**
	 * Method 'setAlphaSeq'
	 * 
	 * @param alphaSeq
	 */
	public void setAlphaSeq(String alphaSeq)
	{
		this.alphaSeq = alphaSeq;
	}
}
