/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.bsva.dcms.commons.dto;

import java.io.Serializable;
import java.util.*;

public class CsfMastercardOptionsDTO implements Serializable
{
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/** 
	 * This attribute maps to the column BANK_CODE in the CSF_MASTERCARD_OPTIONS table.
	 */
	protected int bankCode;

	/** 
	 * This attribute maps to the column RECORD_READ_START_BYTE in the CSF_MASTERCARD_OPTIONS table.
	 */
	protected int recordReadStartByte;

	/** 
	 * This attribute maps to the column RECORD_WRITE_START_BYTE in the CSF_MASTERCARD_OPTIONS table.
	 */
	protected int recordWriteStartByte;

	/** 
	 * This attribute maps to the column RECORD_LEAD_BYTES in the CSF_MASTERCARD_OPTIONS table.
	 */
	protected byte[] recordLeadBytes;

	/** 
	 * This attribute maps to the column EOL_PRESENT in the CSF_MASTERCARD_OPTIONS table.
	 */
	protected String eolPresent;

	/** 
	 * This attribute maps to the column BITMAP_BINARY_TEXT in the CSF_MASTERCARD_OPTIONS table.
	 */
	protected String bitmapBinaryText;

	/**
	 * Method 'CsfMastercardOptions'
	 * 
	 */
	public CsfMastercardOptionsDTO()
	{
	}

	/**
	 * Method 'getBankCode'
	 * 
	 * @return int
	 */
	public int getBankCode()
	{
		return bankCode;
	}

	/**
	 * Method 'setBankCode'
	 * 
	 * @param bankCode
	 */
	public void setBankCode(int bankCode)
	{
		this.bankCode = bankCode;
	}

	/**
	 * Method 'getRecordReadStartByte'
	 * 
	 * @return int
	 */
	public int getRecordReadStartByte()
	{
		return recordReadStartByte;
	}

	/**
	 * Method 'setRecordReadStartByte'
	 * 
	 * @param recordReadStartByte
	 */
	public void setRecordReadStartByte(int recordReadStartByte)
	{
		this.recordReadStartByte = recordReadStartByte;
	}

	/**
	 * Method 'getRecordWriteStartByte'
	 * 
	 * @return int
	 */
	public int getRecordWriteStartByte()
	{
		return recordWriteStartByte;
	}

	/**
	 * Method 'setRecordWriteStartByte'
	 * 
	 * @param recordWriteStartByte
	 */
	public void setRecordWriteStartByte(int recordWriteStartByte)
	{
		this.recordWriteStartByte = recordWriteStartByte;
	}

	/**
	 * Method 'getRecordLeadBytes'
	 * 
	 * @return byte[]
	 */
	public byte[] getRecordLeadBytes()
	{
		return recordLeadBytes;
	}

	/**
	 * Method 'setRecordLeadBytes'
	 * 
	 * @param recordLeadBytes
	 */
	public void setRecordLeadBytes(byte[] recordLeadBytes)
	{
		this.recordLeadBytes = recordLeadBytes;
	}

	/**
	 * Method 'getEolPresent'
	 * 
	 * @return String
	 */
	public String getEolPresent()
	{
		return eolPresent;
	}

	/**
	 * Method 'setEolPresent'
	 * 
	 * @param eolPresent
	 */
	public void setEolPresent(String eolPresent)
	{
		this.eolPresent = eolPresent;
	}

	/**
	 * Method 'getBitmapBinaryText'
	 * 
	 * @return String
	 */
	public String getBitmapBinaryText()
	{
		return bitmapBinaryText;
	}

	/**
	 * Method 'setBitmapBinaryText'
	 * 
	 * @param bitmapBinaryText
	 */
	public void setBitmapBinaryText(String bitmapBinaryText)
	{
		this.bitmapBinaryText = bitmapBinaryText;
	}
}
