/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.bsva.dcms.commons.dto;


import java.io.Serializable;
import java.util.*;
import java.util.Date;

public class CsfPublicHolidaysDTO implements Serializable
{
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/** 
	 * This attribute maps to the column PROCESS_DATE in the CSF_PUBLIC_HOLIDAYS table.
	 */
	protected Date processDate;

	/** 
	 * This attribute maps to the column PUBLIC_HOLIDAY_INDICATOR in the CSF_PUBLIC_HOLIDAYS table.
	 */
	protected String publicHolidayIndicator;

	/**
	 * Method 'CsfPublicHolidays'
	 * 
	 */
	public CsfPublicHolidaysDTO()
	{
	}

	/**
	 * Method 'getProcessDate'
	 * 
	 * @return Date
	 */
	public Date getProcessDate()
	{
		return processDate;
	}

	/**
	 * Method 'setProcessDate'
	 * 
	 * @param processDate
	 */
	public void setProcessDate(Date processDate)
	{
		this.processDate = processDate;
	}

	/**
	 * Method 'getPublicHolidayIndicator'
	 * 
	 * @return String
	 */
	public String getPublicHolidayIndicator()
	{
		return publicHolidayIndicator;
	}

	/**
	 * Method 'setPublicHolidayIndicator'
	 * 
	 * @param publicHolidayIndicator
	 */
	public void setPublicHolidayIndicator(String publicHolidayIndicator)
	{
		this.publicHolidayIndicator = publicHolidayIndicator;
	}
}
