/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.bsva.dcms.commons.dto;

import java.io.Serializable;
import java.util.*;

public class CsfProcessScheduleDTO implements Serializable
{
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/** 
	 * This attribute maps to the column DAY_NUMBER in the CSF_PROCESS_SCHEDULE table.
	 */
	protected int dayNumber;

	/** 
	 * This attribute maps to the column PROCESS_INDICATOR in the CSF_PROCESS_SCHEDULE table.
	 */
	protected String processIndicator;

	/**
	 * Method 'CsfProcessSchedule'
	 * 
	 */
	public CsfProcessScheduleDTO()
	{
	}

	/**
	 * Method 'getDayNumber'
	 * 
	 * @return int
	 */
	public int getDayNumber()
	{
		return dayNumber;
	}

	/**
	 * Method 'setDayNumber'
	 * 
	 * @param dayNumber
	 */
	public void setDayNumber(int dayNumber)
	{
		this.dayNumber = dayNumber;
	}

	/**
	 * Method 'getProcessIndicator'
	 * 
	 * @return String
	 */
	public String getProcessIndicator()
	{
		return processIndicator;
	}

	/**
	 * Method 'setProcessIndicator'
	 * 
	 * @param processIndicator
	 */
	public void setProcessIndicator(String processIndicator)
	{
		this.processIndicator = processIndicator;
	}

}
