/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.bsva.dcms.commons.dto;

import java.io.Serializable;
import java.util.*;

public class CsfSystemServiceDTO implements Serializable
{
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/** 
	 * This attribute maps to the column SERVICE_CODE in the CSF_SYSTEM_SERVICE table.
	 */
	protected String serviceCode;

	/**
	 * Method 'CsfSystemService'
	 * 
	 */
	public CsfSystemServiceDTO()
	{
	}

	/**
	 * Method 'getServiceCode'
	 * 
	 * @return String
	 */
	public String getServiceCode()
	{
		return serviceCode;
	}

	/**
	 * Method 'setServiceCode'
	 * 
	 * @param serviceCode
	 */
	public void setServiceCode(String serviceCode)
	{
		this.serviceCode = serviceCode;
	}

}
