/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.bsva.dcms.commons.dto;

import java.io.Serializable;
import java.util.*;
import java.util.Date;

public class CsfStatusCodesDTO implements Serializable
{
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/** 
	 * This attribute maps to the column STATUS_CODE in the CSF_STATUS_CODES table.
	 */
	protected String statusCode;

	/** 
	 * This attribute maps to the column STATUS_DESCRIPTION in the CSF_STATUS_CODES table.
	 */
	protected String statusDescription;

	/** 
	 * This attribute maps to the column CREATED_BY in the CSF_STATUS_CODES table.
	 */
	protected String createdBy;

	/** 
	 * This attribute maps to the column CREATED_DATE in the CSF_STATUS_CODES table.
	 */
	protected Date createdDate;

	/** 
	 * This attribute maps to the column MODIFIED_BY in the CSF_STATUS_CODES table.
	 */
	protected String modifiedBy;

	/** 
	 * This attribute maps to the column MODIFIED_DATE in the CSF_STATUS_CODES table.
	 */
	protected Date modifiedDate;

	/**
	 * Method 'CsfStatusCodes'
	 * 
	 */
	public CsfStatusCodesDTO()
	{
	}

	/**
	 * Method 'getStatusCode'
	 * 
	 * @return String
	 */
	public String getStatusCode()
	{
		return statusCode;
	}

	/**
	 * Method 'setStatusCode'
	 * 
	 * @param statusCode
	 */
	public void setStatusCode(String statusCode)
	{
		this.statusCode = statusCode;
	}

	/**
	 * Method 'getStatusDescription'
	 * 
	 * @return String
	 */
	public String getStatusDescription()
	{
		return statusDescription;
	}

	/**
	 * Method 'setStatusDescription'
	 * 
	 * @param statusDescription
	 */
	public void setStatusDescription(String statusDescription)
	{
		this.statusDescription = statusDescription;
	}

	/**
	 * Method 'getCreatedBy'
	 * 
	 * @return String
	 */
	public String getCreatedBy()
	{
		return createdBy;
	}

	/**
	 * Method 'setCreatedBy'
	 * 
	 * @param createdBy
	 */
	public void setCreatedBy(String createdBy)
	{
		this.createdBy = createdBy;
	}

	/**
	 * Method 'getCreatedDate'
	 * 
	 * @return Date
	 */
	public Date getCreatedDate()
	{
		return createdDate;
	}

	/**
	 * Method 'setCreatedDate'
	 * 
	 * @param createdDate
	 */
	public void setCreatedDate(Date createdDate)
	{
		this.createdDate = createdDate;
	}

	/**
	 * Method 'getModifiedBy'
	 * 
	 * @return String
	 */
	public String getModifiedBy()
	{
		return modifiedBy;
	}

	/**
	 * Method 'setModifiedBy'
	 * 
	 * @param modifiedBy
	 */
	public void setModifiedBy(String modifiedBy)
	{
		this.modifiedBy = modifiedBy;
	}

	/**
	 * Method 'getModifiedDate'
	 * 
	 * @return Date
	 */
	public Date getModifiedDate()
	{
		return modifiedDate;
	}

	/**
	 * Method 'setModifiedDate'
	 * 
	 * @param modifiedDate
	 */
	public void setModifiedDate(Date modifiedDate)
	{
		this.modifiedDate = modifiedDate;
	}

}
