/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.bsva.dcms.commons.dto;

import java.io.Serializable;
import java.util.*;
import java.util.Date;
import java.math.BigDecimal;

public class CsoSystemControlsDTO implements Serializable
{
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/** 
	 * This attribute maps to the column PROCESS_DATE in the CSO_SYSTEM_CONTROLS table.
	 */
	protected Date processDate;

	/** 
	 * This attribute maps to the column SYSTEM_FUNCTION in the CSO_SYSTEM_CONTROLS table.
	 */
	protected String systemFunction;

	/** 
	 * This attribute maps to the column SERVICE in the CSO_SYSTEM_CONTROLS table.
	 */
	protected String service;

	/** 
	 * This attribute maps to the column SUB_SERVICE in the CSO_SYSTEM_CONTROLS table.
	 */
	protected String subService;

	/** 
	 * This attribute maps to the column OUTPUT_DATE in the CSO_SYSTEM_CONTROLS table.
	 */
	protected Date outputDate;

	/** 
	 * This attribute maps to the column EFFECTIVE_ACTION_DATE in the CSO_SYSTEM_CONTROLS table.
	 */
	protected Date effectiveActionDate;

	/** 
	 * This attribute maps to the column DB_VOLUME in the CSO_SYSTEM_CONTROLS table.
	 */
	protected long dbVolume;

	/** 
	 * This attribute represents whether the primitive attribute dbVolume is null.
	 */
	protected boolean dbVolumeNull = true;

	/** 
	 * This attribute maps to the column DB_AMOUNT in the CSO_SYSTEM_CONTROLS table.
	 */
	protected BigDecimal dbAmount;

	/** 
	 * This attribute maps to the column CR_VOLUME in the CSO_SYSTEM_CONTROLS table.
	 */
	protected long crVolume;

	/** 
	 * This attribute represents whether the primitive attribute crVolume is null.
	 */
	protected boolean crVolumeNull = true;

	/** 
	 * This attribute maps to the column CR_AMOUNT in the CSO_SYSTEM_CONTROLS table.
	 */
	protected BigDecimal crAmount;

	/**
	 * Method 'CsoSystemControls'
	 * 
	 */
	public CsoSystemControlsDTO()
	{
	}

	/**
	 * Method 'getProcessDate'
	 * 
	 * @return Date
	 */
	public Date getProcessDate()
	{
		return processDate;
	}

	/**
	 * Method 'setProcessDate'
	 * 
	 * @param processDate
	 */
	public void setProcessDate(Date processDate)
	{
		this.processDate = processDate;
	}

	/**
	 * Method 'getSystemFunction'
	 * 
	 * @return String
	 */
	public String getSystemFunction()
	{
		return systemFunction;
	}

	/**
	 * Method 'setSystemFunction'
	 * 
	 * @param systemFunction
	 */
	public void setSystemFunction(String systemFunction)
	{
		this.systemFunction = systemFunction;
	}

	/**
	 * Method 'getService'
	 * 
	 * @return String
	 */
	public String getService()
	{
		return service;
	}

	/**
	 * Method 'setService'
	 * 
	 * @param service
	 */
	public void setService(String service)
	{
		this.service = service;
	}

	/**
	 * Method 'getSubService'
	 * 
	 * @return String
	 */
	public String getSubService()
	{
		return subService;
	}

	/**
	 * Method 'setSubService'
	 * 
	 * @param subService
	 */
	public void setSubService(String subService)
	{
		this.subService = subService;
	}

	/**
	 * Method 'getOutputDate'
	 * 
	 * @return Date
	 */
	public Date getOutputDate()
	{
		return outputDate;
	}

	/**
	 * Method 'setOutputDate'
	 * 
	 * @param outputDate
	 */
	public void setOutputDate(Date outputDate)
	{
		this.outputDate = outputDate;
	}

	/**
	 * Method 'getEffectiveActionDate'
	 * 
	 * @return Date
	 */
	public Date getEffectiveActionDate()
	{
		return effectiveActionDate;
	}

	/**
	 * Method 'setEffectiveActionDate'
	 * 
	 * @param effectiveActionDate
	 */
	public void setEffectiveActionDate(Date effectiveActionDate)
	{
		this.effectiveActionDate = effectiveActionDate;
	}

	/**
	 * Method 'getDbVolume'
	 * 
	 * @return long
	 */
	public long getDbVolume()
	{
		return dbVolume;
	}

	/**
	 * Method 'setDbVolume'
	 * 
	 * @param dbVolume
	 */
	public void setDbVolume(long dbVolume)
	{
		this.dbVolume = dbVolume;
		this.dbVolumeNull = false;
	}

	/**
	 * Method 'setDbVolumeNull'
	 * 
	 * @param value
	 */
	public void setDbVolumeNull(boolean value)
	{
		this.dbVolumeNull = value;
	}

	/**
	 * Method 'isDbVolumeNull'
	 * 
	 * @return boolean
	 */
	public boolean isDbVolumeNull()
	{
		return dbVolumeNull;
	}

	/**
	 * Method 'getDbAmount'
	 * 
	 * @return BigDecimal
	 */
	public BigDecimal getDbAmount()
	{
		return dbAmount;
	}

	/**
	 * Method 'setDbAmount'
	 * 
	 * @param dbAmount
	 */
	public void setDbAmount(BigDecimal dbAmount)
	{
		this.dbAmount = dbAmount;
	}

	/**
	 * Method 'getCrVolume'
	 * 
	 * @return long
	 */
	public long getCrVolume()
	{
		return crVolume;
	}

	/**
	 * Method 'setCrVolume'
	 * 
	 * @param crVolume
	 */
	public void setCrVolume(long crVolume)
	{
		this.crVolume = crVolume;
		this.crVolumeNull = false;
	}

	/**
	 * Method 'setCrVolumeNull'
	 * 
	 * @param value
	 */
	public void setCrVolumeNull(boolean value)
	{
		this.crVolumeNull = value;
	}

	/**
	 * Method 'isCrVolumeNull'
	 * 
	 * @return boolean
	 */
	public boolean isCrVolumeNull()
	{
		return crVolumeNull;
	}

	/**
	 * Method 'getCrAmount'
	 * 
	 * @return BigDecimal
	 */
	public BigDecimal getCrAmount()
	{
		return crAmount;
	}

	/**
	 * Method 'setCrAmount'
	 * 
	 * @param crAmount
	 */
	public void setCrAmount(BigDecimal crAmount)
	{
		this.crAmount = crAmount;
	}

}
