/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.bsva.dcms.commons.dto;

import java.io.Serializable;
import java.util.*;

public class SiteControlsDTO implements Serializable
{
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/** 
	 * This attribute maps to the column SITE_CODE in the SITE_CONTROLS table.
	 */
	protected String siteCode;

	/** 
	 * This attribute maps to the column SITE_NAME in the SITE_CONTROLS table.
	 */
	protected String siteName;

	/** 
	 * This attribute maps to the column DB_NAME in the SITE_CONTROLS table.
	 */
	protected String dbName;

	/** 
	 * This attribute maps to the column MENU_EOD in the SITE_CONTROLS table.
	 */
	protected String menuEod;

	/** 
	 * This attribute maps to the column SPOLOG in the SITE_CONTROLS table.
	 */
	protected String spolog;

	/** 
	 * This attribute maps to the column REPORTS in the SITE_CONTROLS table.
	 */
	protected String reports;

	/** 
	 * This attribute maps to the column APPS in the SITE_CONTROLS table.
	 */
	protected String apps;

	/** 
	 * This attribute maps to the column RECEIVE in the SITE_CONTROLS table.
	 */
	protected String receive;

	/** 
	 * This attribute maps to the column SEND in the SITE_CONTROLS table.
	 */
	protected String send;

	/** 
	 * This attribute maps to the column PREV in the SITE_CONTROLS table.
	 */
	protected String prev;

	/** 
	 * This attribute maps to the column RESTORE in the SITE_CONTROLS table.
	 */
	protected String restore;

	/** 
	 * This attribute maps to the column SYSTEM_STATUS in the SITE_CONTROLS table.
	 */
	protected String systemStatus;

	/** 
	 * This attribute maps to the column DEFAULT_CENTRE in the SITE_CONTROLS table.
	 */
	protected String defaultCentre;

	/**
	 * Method 'SiteControls'
	 * 
	 */
	public SiteControlsDTO()
	{
	}

	/**
	 * Method 'getSiteCode'
	 * 
	 * @return String
	 */
	public String getSiteCode()
	{
		return siteCode;
	}

	/**
	 * Method 'setSiteCode'
	 * 
	 * @param siteCode
	 */
	public void setSiteCode(String siteCode)
	{
		this.siteCode = siteCode;
	}

	/**
	 * Method 'getSiteName'
	 * 
	 * @return String
	 */
	public String getSiteName()
	{
		return siteName;
	}

	/**
	 * Method 'setSiteName'
	 * 
	 * @param siteName
	 */
	public void setSiteName(String siteName)
	{
		this.siteName = siteName;
	}

	/**
	 * Method 'getDbName'
	 * 
	 * @return String
	 */
	public String getDbName()
	{
		return dbName;
	}

	/**
	 * Method 'setDbName'
	 * 
	 * @param dbName
	 */
	public void setDbName(String dbName)
	{
		this.dbName = dbName;
	}

	/**
	 * Method 'getMenuEod'
	 * 
	 * @return String
	 */
	public String getMenuEod()
	{
		return menuEod;
	}

	/**
	 * Method 'setMenuEod'
	 * 
	 * @param menuEod
	 */
	public void setMenuEod(String menuEod)
	{
		this.menuEod = menuEod;
	}

	/**
	 * Method 'getSpolog'
	 * 
	 * @return String
	 */
	public String getSpolog()
	{
		return spolog;
	}

	/**
	 * Method 'setSpolog'
	 * 
	 * @param spolog
	 */
	public void setSpolog(String spolog)
	{
		this.spolog = spolog;
	}

	/**
	 * Method 'getReports'
	 * 
	 * @return String
	 */
	public String getReports()
	{
		return reports;
	}

	/**
	 * Method 'setReports'
	 * 
	 * @param reports
	 */
	public void setReports(String reports)
	{
		this.reports = reports;
	}

	/**
	 * Method 'getApps'
	 * 
	 * @return String
	 */
	public String getApps()
	{
		return apps;
	}

	/**
	 * Method 'setApps'
	 * 
	 * @param apps
	 */
	public void setApps(String apps)
	{
		this.apps = apps;
	}

	/**
	 * Method 'getReceive'
	 * 
	 * @return String
	 */
	public String getReceive()
	{
		return receive;
	}

	/**
	 * Method 'setReceive'
	 * 
	 * @param receive
	 */
	public void setReceive(String receive)
	{
		this.receive = receive;
	}

	/**
	 * Method 'getSend'
	 * 
	 * @return String
	 */
	public String getSend()
	{
		return send;
	}

	/**
	 * Method 'setSend'
	 * 
	 * @param send
	 */
	public void setSend(String send)
	{
		this.send = send;
	}

	/**
	 * Method 'getPrev'
	 * 
	 * @return String
	 */
	public String getPrev()
	{
		return prev;
	}

	/**
	 * Method 'setPrev'
	 * 
	 * @param prev
	 */
	public void setPrev(String prev)
	{
		this.prev = prev;
	}

	/**
	 * Method 'getRestore'
	 * 
	 * @return String
	 */
	public String getRestore()
	{
		return restore;
	}

	/**
	 * Method 'setRestore'
	 * 
	 * @param restore
	 */
	public void setRestore(String restore)
	{
		this.restore = restore;
	}

	/**
	 * Method 'getSystemStatus'
	 * 
	 * @return String
	 */
	public String getSystemStatus()
	{
		return systemStatus;
	}

	/**
	 * Method 'setSystemStatus'
	 * 
	 * @param systemStatus
	 */
	public void setSystemStatus(String systemStatus)
	{
		this.systemStatus = systemStatus;
	}

	/**
	 * Method 'getDefaultCentre'
	 * 
	 * @return String
	 */
	public String getDefaultCentre()
	{
		return defaultCentre;
	}

	/**
	 * Method 'setDefaultCentre'
	 * 
	 * @param defaultCentre
	 */
	public void setDefaultCentre(String defaultCentre)
	{
		this.defaultCentre = defaultCentre;
	}

}
