-- Script 1
 CREATE DATABASE  IF NOT EXISTS `CCCOWNER`;
 grant all privileges on CCCOWNER.* to root@localhost identified by 'password';


USE `CCCOWNER`;

DROP TABLE IF EXISTS `CIS_BINS`;
CREATE TABLE `CIS_BINS` (
  `BIN_NO` VARCHAR(6) NOT NULL,
  `BANK_CODE` INT(11) DEFAULT 0,
  `BIN_DESCRIPTION` VARCHAR(30) DEFAULT NULL,
  `CARD_TYPE` VARCHAR(2) DEFAULT NULL,
  `CREATED_BY` VARCHAR(30) DEFAULT NULL,
  `CREATED_DATE` DATETIME DEFAULT NULL,
  `DELETION_DATE` VARCHAR(8) DEFAULT NULL,
  `CURRENCY_CODE` VARCHAR(3),
  `FLOOR_LIMIT` DECIMAL(19,2) DEFAULT NULL,
  `FUEL_ALLOWED` VARCHAR(1) NOT NULL,
  `ISS_ACQ_BOTH` VARCHAR(1) DEFAULT NULL,
  `LIMIT_1` DECIMAL(19,2) DEFAULT NULL,
  `LIMIT_2` DECIMAL(19,2) DEFAULT NULL,
  `LIVE_DATE` DATETIME NOT NULL,
  `MODIFIED_BY` VARCHAR(30) DEFAULT NULL,
  `MODIFIED_DATE` DATETIME DEFAULT NULL,
  `OLD_CARD_TYPE` VARCHAR(2) DEFAULT NULL,
  `ROUTING` SMALLINT(6) DEFAULT NULL,
  `SUB_SERVICE` VARCHAR(10) DEFAULT NULL
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

DROP TABLE IF EXISTS `CSF_ASCII_EBCDIC`;
CREATE TABLE `CSF_ASCII_EBCDIC` (
  `DECIMAL_VAL` SMALLINT(6) NOT NULL,
  `ASCII_CHAR` VARCHAR(1) DEFAULT NULL,
  `EBCDIC_CHAR` VARCHAR(1) DEFAULT NULL,
  `EBCDIC_INT` SMALLINT(6) DEFAULT NULL
  
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

DROP TABLE IF EXISTS `CSF_BINS`;
CREATE TABLE `CSF_BINS` (
  `BIN_NO` VARCHAR(6) NOT NULL,
  `ACQ_ISS_BOTH` VARCHAR(1) NOT NULL,
  `ACTIVE_IND` VARCHAR(1) DEFAULT NULL,
  `BIN_DESCRIPTION` VARCHAR(30) DEFAULT NULL,
  `CARD_TYPE` VARCHAR(2) DEFAULT NULL,
  `CREATED_BY` VARCHAR(30) DEFAULT NULL,
  `CREATED_DATE` DATETIME DEFAULT NULL,
  `DAYS_BEFOREFINAL_DELETION_DATE` SMALLINT(6) DEFAULT NULL,
  `DAYS_BEFOREFIRST_DELETION_DATE` SMALLINT(6) DEFAULT NULL,
  `FINAL_DELETION_DATE` DATETIME DEFAULT NULL,
  `FIRST_DELETION_DATE` DATETIME DEFAULT NULL,
  `FLOOR_LIMIT` DECIMAL(19,2) DEFAULT NULL,
  `LIMIT_1` DECIMAL(19,2) DEFAULT NULL,
  `LIMIT_2` DECIMAL(19,2) DEFAULT NULL,
  `MODIFIED_BY` VARCHAR(30) DEFAULT NULL,
  `MODIFIED_DATE` DATETIME DEFAULT NULL,
  `ROUTING` SMALLINT(6) DEFAULT NULL,
  `SUB_SERVICE` VARCHAR(1) DEFAULT NULL,
  `BANK_CODE` INT(11) DEFAULT NULL,
  `FUEL_ALLOWED` VARCHAR(1) DEFAULT 'N' NOT NULL,
  `OLD_CARD_TYPE` VARCHAR(2)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

DROP TABLE IF EXISTS `CSF_CARD_FEE_BILATERAL`;
CREATE TABLE `CSF_CARD_FEE_BILATERAL` (
  `ACQUIRING_MEMBER` VARCHAR(255) NOT NULL,
  `ISSUING_MEMBER` VARCHAR(255) NOT NULL,
  `TRANSACTION_CODE` VARCHAR(255) NOT NULL,
  `ACTIVE_INDICATOR` VARCHAR(1) NOT NULL,
  `AMOUNT_DIRECTION` SMALLINT(6) NOT NULL,
  `BILL_INDICATOR` VARCHAR(1) NOT NULL,
  `COUNTRY_CODE` VARCHAR(3) DEFAULT NULL,
  `CREATED_BY` VARCHAR(30) DEFAULT NULL,
  `CREATED_DATE` DATETIME DEFAULT NULL,
  `DEST_REPORT` VARCHAR(1) NOT NULL,
  `INPUT_VAT` DECIMAL(19,2),
  `OUTPUT_VAT` DECIMAL(19,2),
  `INTERCHANGE_FEE` DECIMAL(19,2) NOT NULL,
  `INTERCHANGE_FEE_AMOUNT` DECIMAL(19,2) NOT NULL,
  `MODIFIED_BY` VARCHAR(30) DEFAULT NULL,
  `MODIFIED_DATE` DATETIME DEFAULT NULL,
  `CARD_TYPE` SMALLINT(6) NOT NULL
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

DROP TABLE IF EXISTS `CSF_CARD_TYPES`;
CREATE TABLE `CSF_CARD_TYPES` (
  `CARD_TYPE` SMALLINT(6) NOT NULL,
  `CARD_DESCRIPTION` VARCHAR(30) DEFAULT NULL,
  `CREATED_BY` VARCHAR(30) DEFAULT NULL,
  `CREATED_DATE` DATETIME DEFAULT NULL,
  `MODIFIED_BY` VARCHAR(30) DEFAULT NULL,
  `MODIFIED_DATE` DATETIME DEFAULT NULL,
  `PASA_PAYMENT_LIMIT` DECIMAL(19,2) NOT NULL,
  `SUB_SERVICE` VARCHAR(10) DEFAULT NULL
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

DROP TABLE IF EXISTS `CSF_COMPANY_PARAMETERS`;
CREATE TABLE `CSF_COMPANY_PARAMETERS` (
  `COMPANY_NAME` VARCHAR(30) NOT NULL,
  `ADDRESS_1` VARCHAR(30) NOT NULL,
  `ADDRESS_2` VARCHAR(30) NOT NULL,
  `ADDRESS_3` VARCHAR(30) DEFAULT NULL,
  `COMPANY_NAME_ABREV` VARCHAR(3) NOT NULL,
  `CONTACT_NAME` VARCHAR(30) NOT NULL,
  `CREATED_BY` VARCHAR(30) DEFAULT NULL,
  `CREATED_DATE` DATETIME DEFAULT NULL,
  `CURRENCY_CODE` VARCHAR(3) NOT NULL,
  `CURRENCY_CODE_NUMBER` SMALLINT(6) DEFAULT NULL,
  `DIALLING_CODE` VARCHAR(8) NOT NULL,
  `EMAIL_ADDRESS` VARCHAR(30) DEFAULT NULL,
  `FAX_CODE` VARCHAR(8) DEFAULT NULL,
  `FAX_NUMBER` VARCHAR(7) DEFAULT NULL,
  `FLEET_TX_BIND_TIME` SMALLINT(6) DEFAULT NULL,
  `FULL_REPORT_NAME` VARCHAR(60) NOT NULL,
  `INPUT_ID` VARCHAR(2) DEFAULT NULL,
  `INPUT_RECORD_LENGTH` SMALLINT(6) NOT NULL,
  `INSTITUTION_CODE` VARCHAR(2) NOT NULL,
  `INVOICE_DATE` DATETIME DEFAULT NULL,
  `INVOICE_NUMBER` INT(11) DEFAULT NULL,
  `MODIFIED_BY` VARCHAR(30) DEFAULT NULL,
  `MODIFIED_DATE` DATETIME DEFAULT NULL,
  `PREP_CODE` SMALLINT(6) DEFAULT NULL,
  `PREVIOUS_INVOICE_NUMBER` INT(11) DEFAULT NULL,
  `REGISTRATION_NUMBER` VARCHAR(15) NOT NULL,
  `SEQ_NO` BIGINT(20) DEFAULT NULL,
  `TELEPHONE_NUMBER_1` VARCHAR(7) NOT NULL,
  `TEST_LIVE_INDICATOR` VARCHAR(1) NOT NULL,
  `TIERED_CUT_OFF` DECIMAL(19,2) NOT NULL,
  `VALIDATION_CODE` VARCHAR(4) NOT NULL,
  `VAT_NUMBER` VARCHAR(30) NOT NULL,
  `VAT_PERCENT` SMALLINT(6) NOT NULL
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

DROP TABLE IF EXISTS `CSF_DELIVERY_SERVICES`;
CREATE TABLE `CSF_DELIVERY_SERVICES` (
  `ID` DECIMAL(19,2) NOT NULL,
  `ACTIVE_INDICATOR` VARCHAR(1) NOT NULL,
  `BACKUP_FORMAT` VARCHAR(4) NOT NULL,
  `CREATED_BY` VARCHAR(30) DEFAULT NULL,
  `CREATED_DATE` DATETIME DEFAULT NULL,
  `DESCRIPTION` VARCHAR(20) NOT NULL,
  `DESTINATION_CODE` SMALLINT(6) NOT NULL,
  `FILE_FORMAT` VARCHAR(5) NOT NULL,
  `FILENAME_PREFIX` VARCHAR(2) NOT NULL,
  `FORMAT` VARCHAR(4) NOT NULL,
  `HEADER_REFERENCE` VARCHAR(4) DEFAULT NULL,
  `INWARD_OUTWARD_IND` VARCHAR(1) NOT NULL,
  `MEDIA_TYPE` VARCHAR(1) NOT NULL,
  `MODIFIED_BY` VARCHAR(30) DEFAULT NULL,
  `MODIFIED_DATE` DATETIME DEFAULT NULL,
  `SUB_SERVICE` VARCHAR(10) NOT NULL,
  `SERVICE` VARCHAR(4) NOT NULL
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

DROP TABLE IF EXISTS `CSF_DIRECTORIES`;
CREATE TABLE `CSF_DIRECTORIES` (
  `DIRECTORY_NAME` VARCHAR(30) NOT NULL,
  `DIRECTORY_PATH` VARCHAR(30) NOT NULL
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

DROP TABLE IF EXISTS `CSF_DISTRIBUTION_PARAMETERS`;
CREATE TABLE `CSF_DISTRIBUTION_PARAMETERS` (
  `BANK_CODE` SMALLINT(6) NOT NULL,
  `REPORT_NAME` VARCHAR(255) NOT NULL,
  `BANK_DESTINATION` VARCHAR(4) NOT NULL,
  `CREATED_BY` VARCHAR(30) DEFAULT NULL,
  `CREATED_DATE` DATETIME DEFAULT NULL,
  `INWARD_OUTWARD_IND` VARCHAR(1) DEFAULT NULL,
  `MEDIA_TYPE` VARCHAR(1) NOT NULL,
  `MODIFIED_BY` VARCHAR(30) DEFAULT NULL,
  `MODIFIED_DATE` DATETIME DEFAULT NULL,
  `STATUS_CODE` VARCHAR(1) NOT NULL,
  `SUB_SERVICE` VARCHAR(10) DEFAULT NULL,
  `SERVICE` VARCHAR(4) DEFAULT NULL
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

DROP TABLE IF EXISTS `CSF_ERROR_CODES`;
CREATE TABLE `CSF_ERROR_CODES` (
  `ERROR_CODE` INT(11) NOT NULL,
  `ERROR_MESSAGE` VARCHAR(30) NOT NULL,
  `ERROR_REJECT_LEVEL` VARCHAR(4) NOT NULL
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

DROP TABLE IF EXISTS `CSF_FILENAME_LOOKUP`;
CREATE TABLE `CSF_FILENAME_LOOKUP` (
  `ALPHA_SEQ` VARCHAR(3) NOT NULL,
  `NUM_INDEX` BIGINT(20) NOT NULL
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

DROP TABLE IF EXISTS `CSF_INPUT_FILE_FIELDS`;
CREATE TABLE `CSF_INPUT_FILE_FIELDS` (
  `FIELD_CODE` SMALLINT(6) NOT NULL,
  `FIELD_DATA_TYPE` VARCHAR(3) NOT NULL,
  `FIELD_LENGTH` SMALLINT(6) NOT NULL,
  `FIELD_NAME` VARCHAR(30) NOT NULL
) ENGINE=INNODB DEFAULT CHARSET=UTF8;
 
DROP TABLE IF EXISTS `CSF_MASTERCARD_OPTIONS`;
CREATE TABLE `CSF_MASTERCARD_OPTIONS` (
  `BANK_CODE` SMALLINT(6) NOT NULL,
  `BITMAP_BINARY_TEXT` VARCHAR(1) NOT NULL,
  `EOL_PRESENT` VARCHAR(1) NOT NULL,
  `RECORD_LEAD_BYTES` TINYBLOB,
  `RECORD_READ_START_BYTE` SMALLINT(6) NOT NULL,
  `RECORD_WRITE_START_BYTE` SMALLINT(6) NOT NULL
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

DROP TABLE IF EXISTS `CSF_MEMBER_SERVICE`;
CREATE TABLE `CSF_MEMBER_SERVICE` (
  `BANK_CODE` INT(11) NOT NULL,
  `SERVICE` VARCHAR(255) NOT NULL,
  `SUB_SERVICE` VARCHAR(255) NOT NULL,
  `ACCOUNT_NUMBER` VARCHAR(35) DEFAULT NULL,
  `ACQUIRER_IND` VARCHAR(1) DEFAULT NULL,
  `BRANCH_CODE` VARCHAR(6) DEFAULT NULL,
  `CONTACT_NAME` VARCHAR(30) DEFAULT NULL,
  `COUNTRY` VARCHAR(35) DEFAULT NULL,
  `CURRENCY_CODE_VALIDATION_REQ` VARCHAR(1) DEFAULT NULL,
  `EXCEPTION_REPORT_IND` VARCHAR(1) DEFAULT NULL,
  `HEADER01_RECORD_LENGTH` INT(11) NOT NULL,
  `INPUT_CHARSET` VARCHAR(10) NOT NULL,
  `INVOICE_NO_CCR001` INT(11) DEFAULT NULL,
  `ISSUER_IND` VARCHAR(1) DEFAULT NULL,
  `MAX_SIZE_TRANS_FILE` VARCHAR(8) DEFAULT NULL,
  `MEMBER_ADDRESS_1` VARCHAR(30) DEFAULT NULL,
  `MEMBER_ADDRESS_2` VARCHAR(30) DEFAULT NULL,
  `MEMBER_ADDRESS_3` VARCHAR(30) DEFAULT NULL,
  `MEMBER_ADDRESS_4` VARCHAR(30) DEFAULT NULL,
  `MEMBER_NO` VARCHAR(6) DEFAULT NULL,
  `MEMBER_TAPE_ID` VARCHAR(2) DEFAULT NULL,
  `OUTPUT_CHARSET` VARCHAR(10) NOT NULL,
  `OUTPUT_IND` VARCHAR(2) DEFAULT NULL,
  `TITLE` VARCHAR(30) DEFAULT NULL,
  `TRAILER98_RECORD_LENGTH` INT(11) NOT NULL,
  `TRAILER99_RECORD_LENGTH` INT(11) NOT NULL,
  `VAT_REG_NUMBER` VARCHAR(10) DEFAULT NULL,
  `BANK_CODE1` INT(11) DEFAULT NULL,
  `SERVICE1` VARCHAR(255) DEFAULT NULL,
  `SUB_SERVICE1` VARCHAR(255) DEFAULT NULL,
  `SERVICE2` VARCHAR(4) DEFAULT NULL
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

DROP TABLE IF EXISTS `CSF_MEMBERS`;
CREATE TABLE `CSF_MEMBERS` (
  `BANK_CODE` INT(11) NOT NULL,
  `ABBREV_MEMBER_NAME` VARCHAR(12) DEFAULT NULL,
  `CONTACT_NAME` VARCHAR(30) DEFAULT NULL,
  `INCF_OUTPUT_REQUIRED` VARCHAR(1) DEFAULT NULL,
  `MEMBER_ADDRESS_1` VARCHAR(30) DEFAULT NULL,
  `MEMBER_ADDRESS_2` VARCHAR(30) DEFAULT NULL,
  `MEMBER_ADDRESS_3` VARCHAR(30) DEFAULT NULL,
  `MEMBER_ADDRESS_4` VARCHAR(30) DEFAULT NULL,
  `MEMBER_NAME` VARCHAR(30) DEFAULT NULL,
  `MEMBER_NO` VARCHAR(6) DEFAULT NULL,
  `MEMBER_STATUS` VARCHAR(1) DEFAULT NULL,
  `MEMBER_TAPE_ID` VARCHAR(2) DEFAULT NULL,
  `MNEMONIC_MEMBER_NAME` VARCHAR(3) DEFAULT NULL,
  `MONTHS_UNTIL_CIS_BIN_DELETION` SMALLINT(6) DEFAULT NULL,
  `NEG_CARD_DATA_REQUIRED` VARCHAR(1) NOT NULL,
  `ORIGINATING_BANK_ID` VARCHAR(1) DEFAULT NULL,
  `PROCESSOR_ID` BIGINT(20) DEFAULT NULL,
  `TIERED_ITEM_CHARGE` DECIMAL(19,2) DEFAULT NULL,
  `TIERED_ITEM_CHARGE_ABOVE` DECIMAL(19,2) NOT NULL,
  `TIERED_ITEM_CHARGE_BELOW` DECIMAL(19,2) NOT NULL,
  `VAT_REG_NO` VARCHAR(10) DEFAULT NULL
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

DROP TABLE IF EXISTS `CSF_PROCESS_SCHEDULE`;
CREATE TABLE `CSF_PROCESS_SCHEDULE` (
  `DAY_NUMBER` SMALLINT(6) NOT NULL,
  `PROCESS_INDICATOR` VARCHAR(1) NOT NULL
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

DROP TABLE IF EXISTS `CSF_PUBLIC_HOLIDAYS`;
CREATE TABLE `CSF_PUBLIC_HOLIDAYS` (
  `PROCESS_DATE` DATETIME NOT NULL,
  `PUBLIC_HOLIDAY_INDICATOR` VARCHAR(1) NOT NULL
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

DROP TABLE IF EXISTS `CSF_REPORT_NAMES`;
CREATE TABLE `CSF_REPORT_NAMES` (
  `REPORT_NAME` VARCHAR(10) NOT NULL,
  `ACTIVE_INDICATOR` VARCHAR(1) NOT NULL,
  `CREATED_BY` VARCHAR(30) DEFAULT NULL,
  `CREATED_DATE` DATETIME DEFAULT NULL,
  `EXTERNAL_FILENAME_PREFIX` VARCHAR(2) DEFAULT NULL,
  `INTERNAL_FILENAME` VARCHAR(15) DEFAULT NULL,
  `INTERNAL_INDICATOR` VARCHAR(1) NOT NULL,
  `MODIFIED_BY` VARCHAR(30) DEFAULT NULL,
  `MODIFIED_DATE` DATETIME DEFAULT NULL,
  `PROGRAM_NAME` VARCHAR(10) DEFAULT NULL,
  `REPORT_TITLE` VARCHAR(60) NOT NULL
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

DROP TABLE IF EXISTS `CSF_SCHEDULE_TIMES`;
CREATE TABLE `CSF_SCHEDULE_TIMES` (
  `PROCESS` VARCHAR(255) NOT NULL,
  `SERVICE` VARCHAR(255) NOT NULL,
  `SUB_SERVICE` VARCHAR(255) NOT NULL,
  `ACTIVE_IND` VARCHAR(1) NOT NULL,
  `BUSY_IND` VARCHAR(1) NOT NULL,
  `CHECK_POINT` VARCHAR(1) NOT NULL,
  `CHECK_POINT_NAME` VARCHAR(255) DEFAULT NULL,
  `END_TIME` VARCHAR(8) DEFAULT NULL,
  `LAST_RUN_TIME` VARCHAR(20) DEFAULT NULL,
  `PROCESS_DATE` VARCHAR(20) DEFAULT NULL,
  `START_TIME` VARCHAR(8) DEFAULT NULL
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

DROP TABLE IF EXISTS `CSF_SERVICES`;
CREATE TABLE `CSF_SERVICES` (
  `SERVICE_CODE` VARCHAR(255) NOT NULL,
  `SERVICE_NAME` VARCHAR(255) NOT NULL,
  `ACTIVE_INDICATOR` VARCHAR(1) NOT NULL,
  `CREATED_BY` VARCHAR(30) DEFAULT NULL,
  `CREATED_DATE` DATETIME DEFAULT NULL,
  `INPUT_SLA` SMALLINT(6) DEFAULT NULL,
  `MODIFIED_BY` VARCHAR(30) DEFAULT NULL,
  `MODIFIED_DATE` DATETIME DEFAULT NULL,
  `OUTPUT_SLA` SMALLINT(6) DEFAULT NULL,
  `SETTLE_SLA` SMALLINT(6) DEFAULT NULL,
  `SERVICE_CODE1` VARCHAR(4) DEFAULT NULL
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

DROP TABLE IF EXISTS `CSF_STATUS_CODES`;
CREATE TABLE `CSF_STATUS_CODES` (
  `STATUS_CODE` VARCHAR(1) NOT NULL,
  `CREATED_BY` VARCHAR(30) DEFAULT NULL,
  `CREATED_DATE` DATETIME DEFAULT NULL,
  `MODIFIED_BY` VARCHAR(30) DEFAULT NULL,
  `MODIFIED_DATE` DATETIME DEFAULT NULL,
  `STATUS_DESCRIPTION` VARCHAR(30) DEFAULT NULL
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

DROP TABLE IF EXISTS `CSF_SUB_SERVICES`;
CREATE TABLE `CSF_SUB_SERVICES` (
  `SERVICE` VARCHAR(255) NOT NULL,
  `SUB_SERVICE` VARCHAR(255) NOT NULL,
  `ACTIVE_INDICATOR` VARCHAR(1) NOT NULL,
  `CREATED_BY` VARCHAR(30) DEFAULT NULL,
  `CREATED_DATE` DATETIME DEFAULT NULL,
  `DESCRIPTION` VARCHAR(30) DEFAULT NULL,
  `DISPLAY_NAME` VARCHAR(10) DEFAULT NULL,
  `INPUT_SLA` SMALLINT(6) DEFAULT NULL,
  `MODIFIED_BY` VARCHAR(30) DEFAULT NULL,
  `MODIFIED_DATE` DATETIME DEFAULT NULL,
  `OUTPUT_SLA` SMALLINT(6) DEFAULT NULL,
  `PAYMENT_STREAM` VARCHAR(1) NOT NULL,
  `SETTLE_SLA` SMALLINT(6) DEFAULT NULL,
  `SETTLEMENT_NAME` VARCHAR(5) DEFAULT NULL,
  `SERVICE1` VARCHAR(4) DEFAULT NULL
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

DROP TABLE IF EXISTS `CSF_SYSTEM_SERVICE`;
CREATE TABLE `CSF_SYSTEM_SERVICE` (
  `SERVICE_CODE` VARCHAR(4) NOT NULL
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

DROP TABLE IF EXISTS `CSF_SYSTEM_SETTINGS`;
CREATE TABLE `CSF_SYSTEM_SETTINGS` (
  `SETTING_DESCRIPTION` VARCHAR(255) NOT NULL,
  `SETTING_CODE` VARCHAR(10) NOT NULL,
  `SETTING_VALUE` VARCHAR(50) NOT NULL
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

DROP TABLE IF EXISTS `CSF_TRANSACTION_TYPES`;
CREATE TABLE `CSF_TRANSACTION_TYPES` (
  `TRANSACTION_CODE` SMALLINT(6) NOT NULL,
  `CREATED_BY` VARCHAR(30) DEFAULT NULL,
  `CREATED_DATE` DATETIME DEFAULT NULL,
  `FINANCIAL_IND` VARCHAR(1) DEFAULT NULL,
  `MODIFIED_BY` VARCHAR(30) DEFAULT NULL,
  `MODIFIED_DATE` DATETIME DEFAULT NULL,
  `REPORT_SORT_SEQUENCE` SMALLINT(6) NOT NULL,
  `TRANSACTION_DESCRIPTION` VARCHAR(30) DEFAULT NULL
  `AMOUNT_DIRECTION` int(11) DEFAULT NULL,
  `FEE_DIRECTION` int(11) DEFAULT NULL,
  `VAT_DIRECTION` int(11) DEFAULT NULL
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

DROP TABLE IF EXISTS `CSO_INPUT_FILE_CONTROLS`;
CREATE TABLE `CSO_INPUT_FILE_CONTROLS` (
  `SYSTEM_SEQ_NUMBER` BIGINT(20) NOT NULL,
  `CREDIT_VALUE` DECIMAL(19,2) DEFAULT NULL,
  `DEBIT_VALUE` DECIMAL(19,2) DEFAULT NULL,
  `ERROR_FILENAME` VARCHAR(6) DEFAULT NULL,
  `EXCEP_REP_PRODUCED_IND` VARCHAR(1) DEFAULT NULL,
  `EXT_CREDIT_VALUE` DECIMAL(19,2) DEFAULT NULL,
  `EXT_CREDITS` INT(11) DEFAULT NULL,
  `EXT_DEBIT_VALUE` DECIMAL(19,2) DEFAULT NULL,
  `EXT_DEBITS` INT(11) DEFAULT NULL,
  `EXTRACTED_COUNT` INT(11) DEFAULT NULL,
  `FILE_REF_NUMBER` VARCHAR(60) NOT NULL,
  `HASH_TOTAL` BIGINT(20) DEFAULT NULL,
  `LAST_COMMITED_RECORD_POINTER` INT(11) DEFAULT NULL,
  `LAST_FILE_INDICATOR` VARCHAR(1) DEFAULT NULL,
  `LAST_PROCESS_DATE` DATETIME DEFAULT NULL,
  `LOAD_DATE` DATETIME DEFAULT NULL,
  `NEGATIVE_CARD_COUNT` INT(11) DEFAULT NULL,
  `NEGATIVE_DUPLICATE_COUNT` INT(11) DEFAULT NULL,
  `NEXT_OUTPUT_DATE` DATETIME DEFAULT NULL,
  `NUMBER_CREDITS` INT(11) DEFAULT NULL,
  `NUMBER_DEBITS` INT(11) DEFAULT NULL,
  `NUMBER_OF_RECS` INT(11) DEFAULT NULL,
  `ODS_DATA_STATUS` VARCHAR(1) NOT NULL,
  `ORIGINATING_MEMBER` SMALLINT(6) DEFAULT NULL,
  `OUTPUT_DATE` DATETIME DEFAULT NULL,
  `PROCESS_STATUS` VARCHAR(1) DEFAULT NULL,
  `SERVICE` VARCHAR(4) DEFAULT NULL,
  `SETTLEMENT_COUNT` INT(11) DEFAULT NULL,
  `SUB_SERVICE` VARCHAR(10) DEFAULT NULL,
  `IS_BILLED` VARCHAR(1) DEFAULT 'N',
  `IS_PRE_EXTRACTED` VARCHAR(1) DEFAULT 'N' 
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

DROP TABLE IF EXISTS `CSO_NEGCARD_INFO`;
CREATE TABLE `CSO_NEGCARD_INFO` (
  `FILE_ORIGINATOR` SMALLINT(6) NOT NULL,
  `OUTPUT_DATE` VARCHAR(255) NOT NULL,
  `NEG_CARD_COUNT` BIGINT(20) NOT NULL
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

DROP TABLE IF EXISTS `CSO_ODS_FILE_TO_LOAD`;
CREATE TABLE `CSO_ODS_FILE_TO_LOAD` (
  `FILE_REF_NUMBER` VARCHAR(20) NOT NULL,
  `FILEFORMAT` VARCHAR(5) NOT NULL,
  `FILENAME` VARCHAR(20) NOT NULL,
  `SEQ_NO` INT(11) NOT NULL,
  `STATUS` VARCHAR(1) NOT NULL
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

DROP TABLE IF EXISTS `CSO_OUTPUT_CONTROLS`;
CREATE TABLE `CSO_OUTPUT_CONTROLS` (
  `FILENAME_DESCRIPTION` VARCHAR(50) NOT NULL,
  `BANK_CODE` VARCHAR(255) NOT NULL,
  `CR_VALUE` DECIMAL(19,2) DEFAULT NULL,
  `CR_VOLUME` BIGINT(20) DEFAULT NULL,
  `DISTRIBUTION_CODE` VARCHAR(2) NOT NULL,
  `DR_VALUE` DECIMAL(19,2) DEFAULT NULL,
  `DR_VOLUME` BIGINT(20) DEFAULT NULL,
  `END_TIME` DATETIME DEFAULT NULL,
  `FILENAME_PREFIX` VARCHAR(2) NOT NULL,
  `FULLFILEIND` VARCHAR(1) DEFAULT NULL,
  `HASH_TOTAL_98` BIGINT(20) DEFAULT NULL,
  `HASH_TOTAL_99` BIGINT(20) DEFAULT NULL,
  `LAST_FILE_INDICATOR` VARCHAR(1) NOT NULL,
  `NEG_CARD_COUNT` BIGINT(20) NOT NULL,
  `ORIGINATING_BANK_ID` VARCHAR(2) DEFAULT NULL,
  `ORIGINATING_MEMBER` SMALLINT(6) DEFAULT NULL,
  `RECORD_COUNT` INT(11) DEFAULT NULL,
  `SEQ_NUMBER` VARCHAR(3) NOT NULL,
  `SERVICE` VARCHAR(4) NOT NULL,
  `START_TIME` DATETIME DEFAULT NULL,
  `STATUS_CODE` VARCHAR(1) NOT NULL,
  `SUB_SERVICE` VARCHAR(10) NOT NULL,
  `TRANSMISSION_DATE` DATETIME DEFAULT NULL
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

DROP TABLE IF EXISTS `CSO_PAYMENT_INSTRUCTIONS_MCARD`;
CREATE TABLE `CSO_PAYMENT_INSTRUCTIONS_MCARD` (
  `FILE_REF_NUMBER1` VARCHAR(255) NOT NULL,
  `SYSTEM_SEQ_NUMBER2` BIGINT(20) NOT NULL,
  `ACQUIRER_MEMBER` SMALLINT(6) DEFAULT NULL,
  `CARD_TYPE` VARCHAR(2) DEFAULT NULL,
  `CASHBACK_PURCHASE` VARCHAR(1) NOT NULL,
  `CASHBACK_PURCHASE_AMNT` DECIMAL(19,2) NOT NULL,
  `FILENAME_DESCRIPTION` VARCHAR(8) NOT NULL,
  `FINANCIAL_INDICATOR` VARCHAR(1) DEFAULT NULL,
  `INPUT_FILE_IDENTIFIER` VARCHAR(8) DEFAULT NULL,
  `IRD` SMALLINT(6) DEFAULT NULL,
  `ISSUER_MEMBER` SMALLINT(6) DEFAULT NULL,
  `MASTERCARD_AMOUNT` DECIMAL(19,2) DEFAULT NULL,
  `MESSAGE_TYPE_INDICATOR` SMALLINT(6) DEFAULT NULL,
  `P10_CARDHOLDER_CONV_RATE` INT(11) DEFAULT NULL,
  `P11_SYSTEM_TRACE_AUDIT_NUMBER` INT(11) DEFAULT NULL,
  `P12_LOCAL_DATE` BIGINT(20) DEFAULT NULL,
  `P13_LOCAL_TIME` INT(11) DEFAULT NULL,
  `P14_EXPIRATION_DATE` INT(11) DEFAULT NULL,
  `P15_SETTLEMENT_DATE` SMALLINT(6) DEFAULT NULL,
  `P16_CONVERSION_DATE` SMALLINT(6) DEFAULT NULL,
  `P17_CAPTURE_DATE` SMALLINT(6) DEFAULT NULL,
  `P18_MERCHANT_TYPE` SMALLINT(6) DEFAULT NULL,
  `P19_ACQ_BANK_INSTITUTION_CODE` SMALLINT(6) DEFAULT NULL,
  `P20_COUNTRY_CODE_PRI_ACC_NO` SMALLINT(6) DEFAULT NULL,
  `P21_FWDING_INST_COUNTRY_CODE` SMALLINT(6) DEFAULT NULL,
  `P22_POINT_OF_SALE_DATA` VARCHAR(12) DEFAULT NULL,
  `P23_CARD_SEQUENCE_NUMBER` SMALLINT(6) DEFAULT NULL,
  `P24_FUNCTION_CODE` SMALLINT(6) DEFAULT NULL,
  `P25_MESSAGE_REASON_CODE` SMALLINT(6) DEFAULT NULL,
  `P26_CARD_ACCEPTOR_BUS_CODE` SMALLINT(6) DEFAULT NULL,
  `P27_AUTH_ID_RESPONSE_LENGTH` SMALLINT(6) DEFAULT NULL,
  `P28_TRANSACTION_FEE_AMOUNT` INT(11) DEFAULT NULL,
  `P29_SETTLEMENT_FEE_AMOUNT` INT(11) DEFAULT NULL,
  `P2_PAN` VARCHAR(19) DEFAULT NULL,
  `P2_PAN_LENGTH` SMALLINT(6) DEFAULT NULL,
  `P30_ORIGINAL_AMOUNT` VARCHAR(24) DEFAULT NULL,
  `P31_ACQUIRER_REF_DATA` VARCHAR(23) DEFAULT NULL,
  `P31_ACQUIRER_REF_LENGTH` SMALLINT(6) DEFAULT NULL,
  `P32_ACQUIRING_INST_CODE` BIGINT(20) DEFAULT NULL,
  `P32_ACQUIRING_INST_LENGTH` SMALLINT(6) DEFAULT NULL,
  `P33_FORWARDING_INST_CODE` BIGINT(20) DEFAULT NULL,
  `P33_FORWARDING_INST_LENGTH` SMALLINT(6) DEFAULT NULL,
  `P34_EXTENDED_ACCOUNT_NUMBER` VARCHAR(28) DEFAULT NULL,
  `P35_TRACK_2_DATA` VARCHAR(37) DEFAULT NULL,
  `P36_TRACK_3_DATA` VARCHAR(44) DEFAULT NULL,
  `P37_RETRIEVAL_REF_NUMBER` VARCHAR(12) DEFAULT NULL,
  `P38_APPROVAL_CODE` VARCHAR(6) DEFAULT NULL,
  `P39_RESPONSE_CODE` VARCHAR(2) DEFAULT NULL,
  `P3_PROCESS_CODE` INT(11) DEFAULT NULL,
  `P40_SERVICE_CODE` SMALLINT(6) DEFAULT NULL,
  `P41_CARD_ACCEPTOR_TERMINAL_ID` VARCHAR(8) DEFAULT NULL,
  `P42_CARD_ACCEPTOR_ID` VARCHAR(15) DEFAULT NULL,
  `P43_CARD_ACCEPTOR_LENGTH` SMALLINT(6) DEFAULT NULL,
  `P43_CARD_ACCEPTOR_NAME` VARCHAR(99) DEFAULT NULL,
  `P44_ADDITIONAL_RESPONSE_DATA` VARCHAR(27) DEFAULT NULL,
  `P45_TRACK_1_DATA` VARCHAR(76) DEFAULT NULL,
  `P46_ADDITIONAL_DATA_ISO` VARCHAR(20) DEFAULT NULL,
  `P47_ADDITIONAL_DATA_NATIONAL` VARCHAR(20) DEFAULT NULL,
  `P48_ADDITIONAL_DATA` VARCHAR(250) DEFAULT NULL,
  `P48_ADDITIONAL_DATA_LENGTH` VARCHAR(3) DEFAULT NULL,
  `P49_CURRENCY_CODE` SMALLINT(6) DEFAULT NULL,
  `P4_TRANSACTION_AMOUNT` BIGINT(20) DEFAULT NULL,
  `P50_RECONCILLIATION_CODE` SMALLINT(6) DEFAULT NULL,
  `P51_CARDHOLDER_BILL_CUR_CODE` SMALLINT(6) DEFAULT NULL,
  `P52_PERSONAL_ID_NUMBER` VARCHAR(16) DEFAULT NULL,
  `P53_SECURITY_REL_CONTROL_INFO` BIGINT(20) DEFAULT NULL,
  `P54_ADDITIONAL_AMNT_LENGTH` SMALLINT(6) DEFAULT NULL,
  `P54_ADDITIONAL_AMOUNTS` VARCHAR(23) DEFAULT NULL,
  `P55_ICC_LENGTH` SMALLINT(6) DEFAULT NULL,
  `P55_ICC_SYS_DATA_RAW` LONGBLOB,
  `P55_ICC_SYSTEM_RELATED_DATA` VARCHAR(255) DEFAULT NULL,
  `P5_RECONCLLIATION_AMOUNT` BIGINT(20) DEFAULT NULL,
  `P62_ADD_LEN` SMALLINT(6) DEFAULT NULL,
  `P62_ADDITIONAL_DATA` VARCHAR(43) DEFAULT NULL,
  `P63_TRANSACTION_LIFE_CYCLE_ID` VARCHAR(19) DEFAULT NULL,
  `P63_TX_LIFE_CYCLE_ID_LENGTH` SMALLINT(6) DEFAULT NULL,
  `P64_PRIMARY_MAC` VARCHAR(16) DEFAULT NULL,
  `P6_CARDHOLDER_BILLING` BIGINT(20) DEFAULT NULL,
  `P7_TRANSCTION_DATE_AND_TIME` BIGINT(20) DEFAULT NULL,
  `P8_ICCR_AMOUNT` INT(11) DEFAULT NULL,
  `P9_RECON_CONVERSION_RATE` INT(11) DEFAULT NULL,
  `PRIMARY_BITMAP` VARCHAR(64) NOT NULL,
  `PROCESS_STATUS` VARCHAR(1) DEFAULT NULL,
  `RECORD_ID` SMALLINT(6) DEFAULT NULL,
  `S100_RCVING_INST_ID_CODE` BIGINT(20) DEFAULT NULL,
  `S100_RII_LEN` SMALLINT(6) DEFAULT NULL,
  `S101_FILE_NAME` VARCHAR(4) DEFAULT NULL,
  `S102_ACCOUNT_IDENTIFICATION_1` VARCHAR(28) DEFAULT NULL,
  `S103_ACCOUNT_IDENTIFICATION_2` VARCHAR(28) DEFAULT NULL,
  `S104_TRANSACTION_DESCRIPTION` VARCHAR(30) DEFAULT NULL,
  `S111_AMT_CURRENCY_CONVERSION` VARCHAR(12) DEFAULT NULL,
  `S111_LENGTH` SMALLINT(6) DEFAULT NULL,
  `S123_ADD_LEN` SMALLINT(6) DEFAULT NULL,
  `S123_ADDITIONAL_DATA` VARCHAR(43) DEFAULT NULL,
  `S124_ADD_LEN` SMALLINT(6) DEFAULT NULL,
  `S124_ADDITIONAL_DATA` VARCHAR(43) DEFAULT NULL,
  `S125_ADD_LEN` SMALLINT(6) DEFAULT NULL,
  `S125_ADDITIONAL_DATA` VARCHAR(43) DEFAULT NULL,
  `S127_NETWORK_DATA` VARCHAR(43) DEFAULT NULL,
  `S66_SETTLEMNT_CODE` VARCHAR(1) DEFAULT NULL,
  `S67_EXTENDED_PAYMENT_CODE` SMALLINT(6) DEFAULT NULL,
  `S68_REC_INST_COUNTRY_CODE` SMALLINT(6) DEFAULT NULL,
  `S69_SETTLE_INST_COUNTRY_CODE` SMALLINT(6) DEFAULT NULL,
  `S70_NETWORK_MAN_COUNTRY_CODE` SMALLINT(6) DEFAULT NULL,
  `S71_MESSAGE_NUMBER` INT(11) DEFAULT NULL,
  `S72_DATA_LEN` SMALLINT(6) DEFAULT NULL,
  `S72_DATA_RECORD` VARCHAR(100) DEFAULT NULL,
  `S73_ACTION_DATE` INT(11) DEFAULT NULL,
  `S74_NO_OF_CREDITS` BIGINT(20) DEFAULT NULL,
  `S75_REVERSAL_NO_OF_CREDITS` BIGINT(20) DEFAULT NULL,
  `S76_NO_OF_DEBITS` BIGINT(20) DEFAULT NULL,
  `S77_REVERSAL_NO_OF_DEBITS` BIGINT(20) DEFAULT NULL,
  `S78_NUMBER_TRANSFERS` BIGINT(20) DEFAULT NULL,
  `S79_REVERSAL_NUMBER_TRANSFERS` BIGINT(20) DEFAULT NULL,
  `S80_NUMBER_ENQUIRIES` BIGINT(20) DEFAULT NULL,
  `S81_NUMBER_AUTHORISATIONS` BIGINT(20) DEFAULT NULL,
  `S82_PROCESSING_FEE_CREDITS` BIGINT(20) DEFAULT NULL,
  `S83_TRANSACTION_FEE_CREDITS` BIGINT(20) DEFAULT NULL,
  `S84_PROCESSING_FEE_DEBITS` BIGINT(20) DEFAULT NULL,
  `S85_TRANSCTION_FEE_AMOUNTS` BIGINT(20) DEFAULT NULL,
  `S86_AMOUNT_CREDITS` BIGINT(20) DEFAULT NULL,
  `S87_REVERSAL_AMOUNT_CREDITS` BIGINT(20) DEFAULT NULL,
  `S88_AMOUNT_DEBITS` BIGINT(20) DEFAULT NULL,
  `S89_REVERSAL_AMOUNT_DEBITS` BIGINT(20) DEFAULT NULL,
  `S90_ORIGINATING_DATA_ELEMENTS` BIGINT(20) DEFAULT NULL,
  `S91_FILE_UPDATE_CODE` VARCHAR(1) DEFAULT NULL,
  `S92_FILES_SECURITY_CODE` VARCHAR(2) DEFAULT NULL,
  `S93_LENGTH` SMALLINT(6) DEFAULT NULL,
  `S93_TRANSACTION_DEST_INST_ID` BIGINT(20) DEFAULT NULL,
  `S94_LENGTH` SMALLINT(6) DEFAULT NULL,
  `S94_TRANSACTION_ORIG_INST_ID` VARCHAR(11) DEFAULT NULL,
  `S95_CARD_ISS_REF_DATA_LENGTH` SMALLINT(6) DEFAULT NULL,
  `S95_CARD_ISSUER_REF_DATA` VARCHAR(10) DEFAULT NULL,
  `S96_MESSAGE_SECURITY_CODE` VARCHAR(16) DEFAULT NULL,
  `S97_NET_SETTLEMENT_AMOUNT` BIGINT(20) DEFAULT NULL,
  `S98_PAYEE` VARCHAR(25) DEFAULT NULL,
  `S99_SETTLEMENT_INST_ID_CODE` BIGINT(20) DEFAULT NULL,
  `SECONDARY_BITMAP` VARCHAR(64) NOT NULL,
  `SEQ_NO` BIGINT(20) DEFAULT NULL,
  `SERVICE_CODE` VARCHAR(4) DEFAULT NULL,
  `SUB_SERVICE_NAME` VARCHAR(10) DEFAULT NULL,
  `TRANSACTION_CODE` SMALLINT(6) DEFAULT NULL
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

DROP TABLE IF EXISTS `CSO_PAYMENT_INSTRUCTIONS_VISA`;
CREATE TABLE `CSO_PAYMENT_INSTRUCTIONS_VISA` (
  `INPUT_FILE_IDENTIFIER` VARCHAR(255) NOT NULL,
  `INPUT_SEQ_NUMBER` BIGINT(20) NOT NULL,
  `ACCOUNT_NUMBER` VARCHAR(16) DEFAULT NULL,
  `ACQUIRER_COUNTRY_CODE` VARCHAR(3) DEFAULT NULL,
  `ACQUIRER_MEMBER` SMALLINT(6) DEFAULT NULL,
  `CARD_TRANSACTION` VARCHAR(168) NOT NULL,
  `CARD_TYPE` VARCHAR(2) DEFAULT NULL,
  `CASHBACK_PURCHASE` VARCHAR(1) NOT NULL,
  `CASHBACK_PURCHASE_AMNT` DECIMAL(19,2) NOT NULL,
  `EXCHANGE_RATE` BIGINT(20) DEFAULT NULL,
  `FILE_REF_NUMBER` VARCHAR(16) NOT NULL,
  `FILENAME_DESCRIPTION` VARCHAR(8) DEFAULT NULL,
  `FINANCIAL_INDICATOR` VARCHAR(1) DEFAULT NULL,
  `ISSUER_COUNTRY_CODE` VARCHAR(3) DEFAULT NULL,
  `ISSUER_MEMBER` SMALLINT(6) DEFAULT NULL,
  `OUTPUT_DATE` DATETIME DEFAULT NULL,
  `PROCESS_STATUS` VARCHAR(1) DEFAULT NULL,
  `SERVICE` VARCHAR(4) DEFAULT NULL,
  `SETTLEMENT_DATE` DATETIME DEFAULT NULL,
  `SUB_SERVICE` VARCHAR(10) DEFAULT NULL,
  `SYSTEM_GEN_SEQ_NUMBER` VARCHAR(255) NOT NULL,
  `TRANSACTION_CODE` VARCHAR(2) DEFAULT NULL,
  `TRANSACTION_CODE_NUMBER` SMALLINT(6) DEFAULT NULL,
  `TRANSACTION_CODE_QUALIFIER` SMALLINT(6) DEFAULT NULL,
  `VISA_AMOUNT` DECIMAL(19,2) DEFAULT NULL,
  `XBORDER_ISSUER_COUNTRY_CODE` VARCHAR(3) DEFAULT NULL,
  `XBORDER_ISSUER_MEMBER` SMALLINT(6) DEFAULT NULL
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

DROP TABLE IF EXISTS `CSO_PAYMENT_MCARD_PDS`;
CREATE TABLE `CSO_PAYMENT_MCARD_PDS` (
  `PDS_NUMBER` SMALLINT(6) NOT NULL,
  `SYSTEM_SEQ_NUMBER` BIGINT(20) NOT NULL,
  `PDS_DATA` VARCHAR(999) DEFAULT NULL,
  `PDS_LENGTH` SMALLINT(6) NOT NULL
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

DROP TABLE IF EXISTS `CSO_PROGRAM_CONTROLS`;
CREATE TABLE `CSO_PROGRAM_CONTROLS` (
  `ARB_DATA` VARCHAR(255) NOT NULL,
  `PROGRAM_NAME` VARCHAR(255) NOT NULL,
  `END_TIME` DATETIME DEFAULT NULL,
  `EXECUTION_AVERAGE` DECIMAL(19,2) DEFAULT NULL,
  `EXECUTION_LAST` DECIMAL(19,2) DEFAULT NULL,
  `PAYMENT_STREAM` VARCHAR(4) DEFAULT NULL,
  `SEQ_NO` SMALLINT(6) DEFAULT NULL,
  `SERVICE_CODE` VARCHAR(4) DEFAULT NULL,
  `START_TIME` DATETIME DEFAULT NULL,
  `STATUS` VARCHAR(1) DEFAULT NULL,
  `SUB_SERVICE_CODE` VARCHAR(10) DEFAULT NULL
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

DROP TABLE IF EXISTS `CSO_SCHEDULE_TIMES`;
CREATE TABLE `CSO_SCHEDULE_TIMES` (
  `PROCESS` VARCHAR(255) NOT NULL,
  `SERVICE` VARCHAR(255) NOT NULL,
  `SUB_SERVICE` VARCHAR(255) NOT NULL,
  `ACTIVE_IND` VARCHAR(1) NOT NULL,
  `BUSY_IND` VARCHAR(1) NOT NULL,
  `CHECK_POINT` VARCHAR(1) NOT NULL,
  `CHECK_POINT_NAME` VARCHAR(10),
  `END_TIME` VARCHAR(8) DEFAULT NULL,
  `LAST_RUN_TIME` DATETIME DEFAULT NULL,
  `PROCESS_DATE` DATETIME DEFAULT NULL,
  `START_TIME` VARCHAR(8) DEFAULT NULL
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

DROP TABLE IF EXISTS `CSO_SCHEDULED_PROCESSES`;
CREATE TABLE `CSO_SCHEDULED_PROCESSES` (
  `PROCESS_NAME` VARCHAR(15) NOT NULL,
  `ACTIVE_IND` VARCHAR(1) DEFAULT NULL,
  `CLASS_PATH` VARCHAR(100) NOT NULL,
  `PROCESS_FREQUENCY` BIGINT(20) DEFAULT NULL
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

DROP TABLE IF EXISTS `CSO_SEQ_NUMBERS`;
CREATE TABLE `CSO_SEQ_NUMBERS` (
  `DISTRIBUTION_CODE` VARCHAR(255) NOT NULL,
  `EXTERNAL_FILENAME_PREFIX` VARCHAR(255) NOT NULL,
  `LAST_SEQ_NUMBER_USED` SMALLINT(6) NOT NULL
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

DROP TABLE IF EXISTS `CSO_SERVICE_PARAMETERS`;
CREATE TABLE `CSO_SERVICE_PARAMETERS` (
  `PROCESS_DATE` DATETIME NOT NULL,
  `SERVICE` VARCHAR(255) NOT NULL,
  `SUB_SERVICE` VARCHAR(255) NOT NULL,
  `INPUT_REQUEST_CLOSE` VARCHAR(1) DEFAULT NULL,
  `INWARD_STATUS` VARCHAR(1) DEFAULT NULL,
  `OUTWARD_STATUS` VARCHAR(1) DEFAULT NULL,
  `PROCESS_ACTIVE_IND` VARCHAR(1) NOT NULL
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

DROP TABLE IF EXISTS `CSO_SYSTEM_CONTROLS`;
CREATE TABLE `CSO_SYSTEM_CONTROLS` (
  `PROCESS_DATE` DATETIME NOT NULL,
  `SERVICE` VARCHAR(255) NOT NULL,
  `SUB_SERVICE` VARCHAR(255) NOT NULL,
  `SYSTEM_FUNCTION` VARCHAR(255) NOT NULL,
  `CR_AMOUNT` DECIMAL(19,2) DEFAULT NULL,
  `CR_VOLUME` BIGINT(20) DEFAULT NULL,
  `DB_AMOUNT` DECIMAL(19,2) DEFAULT NULL,
  `DB_VOLUME` BIGINT(20) DEFAULT NULL,
  `EFFECTIVE_ACTION_DATE` DATETIME DEFAULT NULL,
  `OUTPUT_DATE` DATETIME DEFAULT NULL
) ENGINE=INNODB DEFAULT CHARSET=UTF8;


DROP TABLE IF EXISTS `CSO_SYSTEM_PARAMETERS`;
CREATE TABLE `CSO_SYSTEM_PARAMETERS` (
  `NEXT_OUTPUT_DATE` DATETIME NOT NULL,
  `CCCORE_INTERVAL` SMALLINT(6) NOT NULL,
  `CIS_DOWNLOAD_IND` VARCHAR(1) NOT NULL,
  `EOD_DONE` VARCHAR(1) DEFAULT NULL,
  `LIVE_TEST_CODE` VARCHAR(1) NOT NULL,
  `PROCESS_ACTIVE_IND` VARCHAR(1) NOT NULL,
  `PROCESS_DATE` DATETIME,
  `RUN_BATCH` VARCHAR(1) DEFAULT NULL,
  `UNIX_SOD_DONE` VARCHAR(1) DEFAULT NULL
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

DROP TABLE IF EXISTS `CSO_TRANSACTIONS`;
CREATE TABLE `CSO_TRANSACTIONS` (
  `SYSTEM_SEQ_NUMBER` BIGINT(20) NOT NULL,
  `ACCOUNT_NUMBER` VARCHAR(19) DEFAULT NULL,
  `ACQUIRER_BIN` INT(11) DEFAULT NULL,
  `ACQUIRER_MEMBER` SMALLINT(6) DEFAULT NULL,
  `BILLING_FEE` DECIMAL(19,2) DEFAULT NULL,
  `BILLING_FEE_AMOUNT` DECIMAL(19,2) DEFAULT NULL,
  `BILLING_VAT` DECIMAL(19,2) DEFAULT NULL,
  `CARD_TYPE` SMALLINT(6) NOT NULL,
  `CASHBACK_AMOUNT` DECIMAL(19,2) NOT NULL,
  `CASHBACK_PRESENT` VARCHAR(1) NOT NULL,
  `CB_BILL_FEE` DECIMAL(19,2) DEFAULT NULL,
  `CB_BILL_FEE_AMNT` DECIMAL(19,2) DEFAULT NULL,
  `CB_BILL_VAT` DECIMAL(19,2) DEFAULT NULL,
  `DEST_REPORT` VARCHAR(1) DEFAULT NULL,
  `EXTRACTIND` VARCHAR(1) DEFAULT NULL,
  `FILE_RECORD_CNT` SMALLINT(6) NOT NULL,
  `FILE_SYSTEM_SEQ_NUMBER` VARCHAR(255) NOT NULL,
  `FLEET_COUNT_TRAN` VARCHAR(1) NOT NULL,
  `FLEET_PRODUCT` VARCHAR(1) DEFAULT NULL,
  `FLEET_SUB_PRODUCT` VARCHAR(2) DEFAULT NULL,
  `INTCHG_RATE_DSGN` SMALLINT(6) DEFAULT NULL,
  `ISSUER_BIN` INT(11) DEFAULT NULL,
  `ISSUER_MEMBER` SMALLINT(6) DEFAULT NULL,
  `MERCHANT_CAT_CODE` SMALLINT(6) DEFAULT NULL,
  `MESSAGE_REASON_CODE` SMALLINT(6) DEFAULT NULL,
  `MESSAGE_TYPE_IND` SMALLINT(6) DEFAULT NULL,
  `OPFILE_NUM_SEQ` INT(11) NOT NULL,
  `OUTPUT_FILENAME` VARCHAR(8) DEFAULT NULL,
  `PROCESS_STATUS` VARCHAR(1) NOT NULL,
  `RECORD_END_BYTE` DECIMAL(19,2) NOT NULL,
  `RECORD_NUMBER` BIGINT(20) NOT NULL,
  `RECORD_START_BYTE` DECIMAL(19,2) NOT NULL,
  `TRANSACTION_AMOUNT` DECIMAL(19,2) NOT NULL,
  `TRANSACTION_CODE` SMALLINT(6) NOT NULL,
  `TRANSACTION_TIME` BIGINT(20) DEFAULT NULL
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

DROP TABLE IF EXISTS `CSO_Z1_Z9_INPUT_OUTPUTS`;
CREATE TABLE `CSO_Z1_Z9_INPUT_OUTPUTS` (
  `FILENAME_DESCRIPTION` VARCHAR(30) NOT NULL,
  `ACQUIRER` SMALLINT(6) DEFAULT NULL,
  `AXD_CREATED_INDICATOR` VARCHAR(1) NOT NULL,
  `BANK_CODE` SMALLINT(6) DEFAULT NULL,
  `CENTRE` SMALLINT(6) NOT NULL,
  `CONTROL_RECORD_COUNT` INT(11) DEFAULT NULL,
  `CR_VALUE` DECIMAL(19,2) DEFAULT NULL,
  `DESTINATION` INT(11) DEFAULT NULL,
  `DISTRIBUTED_INDICATOR` VARCHAR(1) DEFAULT NULL,
  `DR_VALUE` DECIMAL(19,2) DEFAULT NULL,
  `FILE_REF_NUMBER` VARCHAR(16) DEFAULT NULL,
  `HASH_TOTAL` BIGINT(20) DEFAULT NULL,
  `INPUT_OUTPUT_INDICATOR` VARCHAR(1) NOT NULL,
  `INTERNAL_INDICATOR` VARCHAR(1) NOT NULL,
  `ISSUER` SMALLINT(6) DEFAULT NULL,
  `LAST_FILE_INDICATOR` VARCHAR(1) NOT NULL,
  `MEDIA` VARCHAR(1) NOT NULL,
  `NEGATIVE_CARD_COUNT` INT(11) DEFAULT NULL,
  `NO_OF_CREDITS` INT(11) DEFAULT NULL,
  `NO_OF_DEBITS` INT(11) DEFAULT NULL,
  `NUMBER_OF_RECORDS` BIGINT(20) NOT NULL,
  `OPS_DATE` DATETIME DEFAULT NULL,
  `ORA_SEQ_NUMBER` BIGINT(20) NOT NULL,
  `PRINT_CODE` VARCHAR(1) DEFAULT NULL,
  `RECIPIENT_CODE` VARCHAR(1) DEFAULT NULL,
  `REPORT_NAME` VARCHAR(15) DEFAULT NULL,
  `SERVICE` VARCHAR(4) NOT NULL,
  `SUB_SERVICE` VARCHAR(10) NOT NULL,
  `TRANSMIT_INDICATOR` VARCHAR(1) NOT NULL
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

DROP TABLE IF EXISTS `DEL_DELIVERY_FILES_CCC`;
CREATE TABLE `DEL_DELIVERY_FILES_CCC` (
  `FILENAME` VARCHAR(255) NOT NULL,
  `POSITION` INT(11) NOT NULL,
  `QUEUE_FILE_NAME` VARCHAR(255) NOT NULL,
  `APPLICATION` VARCHAR(4) DEFAULT NULL,
  `BACKUP_FORMAT` VARCHAR(4) DEFAULT NULL,
  `BLOCK_FACTOR` SMALLINT(6) DEFAULT NULL,
  `CREATE_TRAILER` VARCHAR(1) DEFAULT NULL,
  `DELIVERY_STATUS` VARCHAR(1) DEFAULT NULL,
  `DELIVERY_TIME` INT(11) DEFAULT NULL,
  `HASH_TOTAL` BIGINT(20) DEFAULT NULL,
  `LAST_FILE` VARCHAR(1) DEFAULT NULL,
  `MEMBER` SMALLINT(6) DEFAULT NULL,
  `NO_OF_CREDITS` INT(11) DEFAULT NULL,
  `NO_OF_DEBITS` INT(11) DEFAULT NULL,
  `NO_OF_RECORDS` INT(11) DEFAULT NULL,
  `OUTPUT_FORMAT` VARCHAR(4) DEFAULT NULL,
  `PRD_DATE` INT(11) DEFAULT NULL,
  `PROGRAM_FROM` VARCHAR(10) DEFAULT NULL,
  `REC_LENGTH` SMALLINT(6) DEFAULT NULL,
  `REJECT_REASON` VARCHAR(24) DEFAULT NULL,
  `REPORT_NAME` VARCHAR(24) DEFAULT NULL,
  `SUB_APPLICATION` VARCHAR(10) DEFAULT NULL,
  `TIME_CREATED` INT(11) DEFAULT NULL,
  `USER_DEST` SMALLINT(6) DEFAULT NULL,
  `VALUE_CREDITS` DECIMAL(19,2) DEFAULT NULL,
  `VALUE_DEBITS` DECIMAL(19,2) DEFAULT NULL,
  `WRITTEN_TO_AXD` VARCHAR(1) DEFAULT NULL,
  `XMIT_IND` VARCHAR(1) DEFAULT NULL
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

DROP TABLE IF EXISTS `HIBERNATE_SEQUENCES`;
CREATE TABLE `HIBERNATE_SEQUENCES` (
  `SEQUENCE_NAME` VARCHAR(255) DEFAULT NULL,
  `SEQUENCE_NEXT_HI_VALUE` INT(11) DEFAULT NULL
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

DROP TABLE IF EXISTS `SITE_CONTROLS`;
CREATE TABLE `SITE_CONTROLS` (
  `SITE_CODE` VARCHAR(10) NOT NULL,
  `APPS` VARCHAR(100) DEFAULT NULL,
  `DB_NAME` VARCHAR(8) NOT NULL,
  `DEFAULT_CENTRE` VARCHAR(3) NOT NULL,
  `MENU_EOD` VARCHAR(1) DEFAULT NULL,
  `PREV` VARCHAR(100) DEFAULT NULL,
  `RECEIVE` VARCHAR(100) DEFAULT NULL,
  `REPORTS` VARCHAR(100) DEFAULT NULL,
  `RESTORE` VARCHAR(100) DEFAULT NULL,
  `SEND` VARCHAR(100) DEFAULT NULL,
  `SITE_NAME` VARCHAR(100) NOT NULL,
  `SPOLOG` VARCHAR(100) DEFAULT NULL,
  `SYSTEM_STATUS` VARCHAR(4) NOT NULL
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

DROP TABLE IF EXISTS `CSS_MONTH_STATS`;
CREATE TABLE `CSS_MONTH_STATS` (
  `PROCESS_DATE` DATE NOT NULL,
	`ISSUER_BIN` VARCHAR(6) NOT NULL,
	`ACQUIRER_BIN` VARCHAR(6) NOT NULL,
	`SERVICE` VARCHAR(4) NOT NULL,
	`SUB_SERVICE` VARCHAR(10) NOT NULL,
	`TRANSACTION_CODE` VARCHAR(2) NOT NULL,
	`PROCESS_STATUS` VARCHAR(1) NOT NULL,
	`CARD_TYPE` VARCHAR(2) NOT NULL,
	`SETTLE_DATE` DATE NOT NULL,
	`TRANSACTION_DATE` DATE,
	`FINANCIAL_IND` VARCHAR(1),
	`MESSAGE_TYPE_IND` INT,
	`PROCESS_CODE` INT,
	`RECORD_ID` INT,
	`REVERSAL_IND` VARCHAR(1),
	`MERCHANT_CAT_CODE` VARCHAR(4) NOT NULL,
	`INTCHG_RATE_DSGN` INT,
	`MESSAGE_REASON_CODE` INT,
	`TOTAL_AMOUNT` DECIMAL(16,2),
	`TOTAL_COUNT` DECIMAL(8,0),
	`BILLING_AMOUNT` DECIMAL(15,5) DEFAULT 0,
	`BILLING_PERC_AMOUNT` DECIMAL(15,5) DEFAULT 0,
	`BILLING_VAT` DECIMAL(15,5) DEFAULT 0,
	`ACQUIRER_MEMBER` INT DEFAULT 0,
	`ISSUER_MEMBER` INT DEFAULT 0
   );

DROP TABLE IF EXISTS `CSF_FTP_CONTROL`;
CREATE TABLE `CSF_FTP_CONTROL` 
(	
	`FTP_CODE` VARCHAR(10), 
	`FTP_COMMAND` VARCHAR(255), 
	`ACTIVE_IND` VARCHAR(1)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

DROP TABLE IF EXISTS `CSO_CORE_PROCESSES`;
CREATE TABLE `CSO_CORE_PROCESSES`
(	
	`PROGRAM_NAME` VARCHAR(40) NOT NULL, 
	`TIME_INTERVAL` INT NOT NULL, 
	`NO_OF_INSTANCE_SET` INT NOT NULL, 
	`NO_OF_INSTANCE_ACTIVE` INT, 
	`ACTIVE_IND` VARCHAR(1) NOT NULL, 
	`SEQUENCE_NUMBER` INT, 
	`PROGRAM_ALIAS` VARCHAR(10)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

DROP TABLE IF EXISTS `CSO_SETTLEMENT_MATRIXES_PROD`;
CREATE TABLE `CSO_SETTLEMENT_MATRIXES_PROD` 
(	
	`ORIGINATING_BANK` INT NOT NULL, 
	`ACTION_DATE` DATE, 
	`HOMING_BANK` INT NOT NULL, 
	`SERVICE` VARCHAR(4) NOT NULL, 
	`SUB_SERVICE` VARCHAR(10) NOT NULL, 
	`CURRENCY_CODE` VARCHAR(3) NOT NULL, 
	`STATUS_CODE` VARCHAR(1) NOT NULL, 
	`SETTLEMENT_IND` VARCHAR(1) NOT NULL, 
	`BANK_OUTPUT_CREATED_IND` VARCHAR(1) NOT NULL, 
	`CR_VALUE_INWARD` DECIMAL(13,2) NOT NULL, 
	`CR_VALUE_OUTWARD` DECIMAL(13,2) NOT NULL, 
	`DR_VALUE_INWARD` DECIMAL(13,2) NOT NULL, 
	`DR_VALUE_OUTWARD` DECIMAL(13,2) NOT NULL, 
	`CR_VOLUME` INT NOT NULL, 
	`DR_VOLUME` INT NOT NULL, 
	`CR_VALUE` DECIMAL(13,2) NOT NULL, 
	`DR_VALUE` DECIMAL(13,2) NOT NULL, 
	`PAYMENT_STREAM` VARCHAR(1) NOT NULL
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

DROP TABLE IF EXISTS `CSF_INSTALLED_COMPONENTS`;
CREATE TABLE `CSF_INSTALLED_COMPONENTS` 
(	
	`COMPONENT_NAME` VARCHAR(20) NOT NULL, 
	`COMPONENT_STALLED` VARCHAR(1) NOT NULL
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

DROP TABLE IF EXISTS `CSF_CHECK_PIONTS`;
CREATE TABLE `CSF_CHECK_PIONTS` 
(	
	`CHECK_POINT_NAME` VARCHAR(10) NOT NULL, 
	`CHECK_POINT_DESCRIPTION` VARCHAR(255) NOT NULL, 
	PRIMARY KEY (`CHECK_POINT_NAME`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

DROP TABLE IF EXISTS `USR_USER_NAMES`;
CREATE TABLE `USR_USER_NAMES` 
(	
	`LOGIN_NAME` VARCHAR(20) NOT NULL, 
	`FULL_NAME` VARCHAR(100) NOT NULL, 
	`LAST_NAME` VARCHAR(100) NOT NULL 
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

DROP TABLE IF EXISTS `CSO_BATCH_PROCESSES`;
CREATE TABLE `CSO_BATCH_PROCESSES` 
(	
	`RUN_ORDER` INT NOT NULL, 
	`PROGRAM_NAME` VARCHAR(40) NOT NULL, 
	`COMPLETED` VARCHAR(1) NOT NULL, 
	`MONTH_END_ONLY` VARCHAR(1) NOT NULL, 
	`PROGRAM_ALIAS` VARCHAR(10) NOT NULL, 
	`INTERFACE` VARCHAR(10) NOT NULL, 
	`ACTIVE` VARCHAR(1) NOT NULL, 
	 PRIMARY KEY (`PROGRAM_ALIAS`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

DROP TABLE IF EXISTS `USR_ACCESS_UNITS`;
CREATE TABLE `USR_ACCESS_UNITS` 
(	
	`ACCESS_UNIT_NAME` VARCHAR(50) NOT NULL, 
	`ACCESS_UNIT_DESC` VARCHAR(250) NOT NULL, 
	`ACCESS_UNIT_IDX` INT NOT NULL, 
	`SYSTEM_NAME` VARCHAR(10) NOT NULL, 
	 PRIMARY KEY (`ACCESS_UNIT_NAME`, `SYSTEM_NAME`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

DROP TABLE IF EXISTS `BOOK`;
CREATE TABLE `BOOK` 
(	
   `ID` VARCHAR(10) NOT NULL, 
   `TITLE` VARCHAR(50) NOT NULL, 
   `AUTHOR` VARCHAR(50) 
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

DROP TABLE IF EXISTS `PLAN_TABLE`;
CREATE TABLE `PLAN_TABLE` 
(	
	`STATEMENT_ID` VARCHAR(30), 
	`TIMESTAMP` DATE, 
	`REMARKS` VARCHAR(80), 
	`OPERATION` VARCHAR(30), 
	`OPTIONS` VARCHAR(30), 
	`OBJECT_NODE` VARCHAR(128), 
	`OBJECT_OWNER` VARCHAR(30), 
	`OBJECT_NAME` VARCHAR(30), 
	`OBJECT_INSTANCE` BIGINT, 
	`OBJECT_TYPE` VARCHAR(30), 
	`OPTIMIZER` VARCHAR(255), 
	`SEARCH_COLUMNS` INT, 
	`ID` BIGINT, 
	`PARENT_ID` BIGINT, 
	`POSITION` BIGINT, 
	`COST` BIGINT, 
	`CARDINALITY` BIGINT, 
	`BYTES` BIGINT, 
	`OTHER_TAG` VARCHAR(255), 
	`PARTITION_START` VARCHAR(255), 
	`PARTITION_STOP` VARCHAR(255), 
	`PARTITION_ID` BIGINT, 
	`OTHER` BIGINT, 
	`DISTRIBUTION` VARCHAR(30)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

DROP TABLE IF EXISTS `CSF_FILENAME_LOOKUP`;
CREATE TABLE `CSF_FILENAME_LOOKUP` 
(	
	`NUM_INDEX` INT NOT NULL, 
	`ALPHA_SEQ` VARCHAR(3) NOT NULL
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

DROP TABLE IF EXISTS `CSF_FLEET_CODES`;
CREATE TABLE `CSF_FLEET_CODES` 
(	
	`MIF_CODE` VARCHAR(2) NOT NULL, 
	`CODE_DESC` VARCHAR(40) NOT NULL, 
	`CREATED_BY` VARCHAR(30) NOT NULL, 
	`CREATED_DATE` DATE NOT NULL, 
	`MODIFIED_BY` VARCHAR(30) NOT NULL, 
	`MODIFIED_DATE` DATE NOT NULL
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

DROP TABLE IF EXISTS `USR_SYSTEMS`;
CREATE TABLE `USR_SYSTEMS` 
(	
   	`FULL_SYSTEM_NAME` VARCHAR(50), 
	`SYSTEM_NAME` VARCHAR(5), 
	 PRIMARY KEY (`SYSTEM_NAME`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

DROP TABLE IF EXISTS `CSF_CASHBACK_MCC`;
CREATE TABLE `CSF_CASHBACK_MCC`
(	
	`CB_MCC` INT NOT NULL, 
	 PRIMARY KEY (`CB_MCC`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

DROP TABLE IF EXISTS `MD_CODE_REGEX`;
CREATE TABLE `MD_CODE_REGEX` 
(	
	`ID` INT NOT NULL, 
	`REGEX` VARCHAR(100) NOT NULL, 
	`DESCRIPTION` VARCHAR(200) NOT NULL
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

DROP TABLE IF EXISTS `CSF_EOD_REPORTS`;
CREATE TABLE `CSF_EOD_REPORTS`
(	
	`REPORT_NAME` VARCHAR(30) NOT NULL, 
	`END_OF_MONTH_ONLY` VARCHAR(1) DEFAULT 'N' NOT NULL, 
	`RUNON_PUBLIC_HOLIDAY` VARCHAR(1) DEFAULT 'N' NOT NULL, 
	 PRIMARY KEY (`REPORT_NAME`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;

ALTER TABLE `CIS_BINS` ADD PRIMARY KEY (`BIN_NO`);
ALTER TABLE `CSF_ASCII_EBCDIC` ADD PRIMARY KEY (`DECIMAL_VAL`);
ALTER TABLE `CSF_BINS` ADD PRIMARY KEY (`BIN_NO`);
ALTER TABLE `CSF_BINS` ADD KEY `FK_KTK9KMHOJH3BP5XDA18DQL7U9` (`BANK_CODE`);
ALTER TABLE `CSF_CARD_FEE_BILATERAL` ADD PRIMARY KEY (`ACQUIRING_MEMBER`,`ISSUING_MEMBER`,`TRANSACTION_CODE`, `CARD_TYPE`);
ALTER TABLE `CSF_CARD_FEE_BILATERAL` ADD KEY `FK_826SN40S69E5W5ULHITY1BJ2H` (`CARD_TYPE`);
ALTER TABLE `CSF_CARD_TYPES` ADD PRIMARY KEY (`CARD_TYPE`);
ALTER TABLE `CSF_COMPANY_PARAMETERS` ADD  PRIMARY KEY (`COMPANY_NAME`);
ALTER TABLE `CSF_DELIVERY_SERVICES` ADD PRIMARY KEY (`ID`);
ALTER TABLE `CSF_DELIVERY_SERVICES` ADD KEY `FK_MA0BA3FHMC58CR7A35L7VFFN1` (`SERVICE`);
ALTER TABLE `CSF_DIRECTORIES` ADD PRIMARY KEY (`DIRECTORY_NAME`);
ALTER TABLE `CSF_DISTRIBUTION_PARAMETERS` ADD PRIMARY KEY (`BANK_CODE`,`REPORT_NAME`);
ALTER TABLE `CSF_DISTRIBUTION_PARAMETERS` ADD KEY `FK_UYEBKCFVH203R1IGLFSJGL80` (`SERVICE`);
ALTER TABLE `CSF_ERROR_CODES` ADD PRIMARY KEY (`ERROR_CODE`);
ALTER TABLE `CSF_FILENAME_LOOKUP` ADD PRIMARY KEY (`ALPHA_SEQ`);
ALTER TABLE `CSF_INPUT_FILE_FIELDS` ADD PRIMARY KEY (`FIELD_CODE`);
ALTER TABLE `CSF_MASTERCARD_OPTIONS` ADD PRIMARY KEY (`BANK_CODE`);
ALTER TABLE `CSF_MEMBER_SERVICE` ADD PRIMARY KEY (`BANK_CODE`,`SERVICE`,`SUB_SERVICE`);
ALTER TABLE `CSF_MEMBER_SERVICE` ADD KEY `FK_RKWH61O5WBN4VMRUBWBV2EG2O` (`BANK_CODE1`);
ALTER TABLE `CSF_MEMBER_SERVICE` ADD KEY `FK_IFYTMEHMRQDVIGXPIGAYYP1OA` (`SERVICE`,`SUB_SERVICE`);
ALTER TABLE `CSF_MEMBER_SERVICE` ADD KEY `FK_6FU4GVQAIJD93V2JMBY79H6HV` (`SERVICE1`,`SUB_SERVICE1`);
ALTER TABLE `CSF_MEMBER_SERVICE` ADD KEY `FK_LAW72TRRYCOVJ9G49EVGLV9N` (`SERVICE2`);
ALTER TABLE `CSF_MEMBERS` ADD PRIMARY KEY (`BANK_CODE`);
ALTER TABLE `CSF_PROCESS_SCHEDULE` ADD PRIMARY KEY (`DAY_NUMBER`);
ALTER TABLE `CSF_PUBLIC_HOLIDAYS` ADD PRIMARY KEY (`PROCESS_DATE`);
ALTER TABLE `CSF_REPORT_NAMES` ADD PRIMARY KEY (`REPORT_NAME`);
ALTER TABLE `CSF_SCHEDULE_TIMES` ADD PRIMARY KEY (`PROCESS`,`SERVICE`,`SUB_SERVICE`); 
ALTER TABLE `CSF_SERVICES` ADD PRIMARY KEY (`SERVICE_CODE`,`SERVICE_NAME`);
ALTER TABLE `CSF_SERVICES` ADD KEY `FK_5IFHNW8VRV3FNFHQRRLI11DTV` (`SERVICE_CODE1`);
ALTER TABLE `CSF_STATUS_CODES` ADD PRIMARY KEY (`STATUS_CODE`);
ALTER TABLE `CSF_SUB_SERVICES` ADD PRIMARY KEY (`SERVICE`,`SUB_SERVICE`);
ALTER TABLE `CSF_SUB_SERVICES` ADD KEY `FK_1KUMSW0PXY99QA3J7P3IAVUC7` (`SERVICE1`);
ALTER TABLE `CSF_SYSTEM_SERVICE` ADD PRIMARY KEY (`SERVICE_CODE`);
ALTER TABLE `CSF_SYSTEM_SETTINGS` ADD PRIMARY KEY (`SETTING_DESCRIPTION`); 
ALTER TABLE `CSF_TRANSACTION_TYPES` ADD PRIMARY KEY (`TRANSACTION_CODE`);
ALTER TABLE `CSO_INPUT_FILE_CONTROLS` ADD PRIMARY KEY (`SYSTEM_SEQ_NUMBER`);
ALTER TABLE `CSO_NEGCARD_INFO` ADD PRIMARY KEY (`FILE_ORIGINATOR`,`OUTPUT_DATE`);
ALTER TABLE `CSO_ODS_FILE_TO_LOAD` ADD PRIMARY KEY (`FILE_REF_NUMBER`);
ALTER TABLE `CSO_OUTPUT_CONTROLS` ADD PRIMARY KEY (`FILENAME_DESCRIPTION`);
ALTER TABLE `CSO_PAYMENT_INSTRUCTIONS_MCARD` ADD PRIMARY KEY (`FILE_REF_NUMBER1`,`SYSTEM_SEQ_NUMBER2`);
ALTER TABLE `CSO_PAYMENT_INSTRUCTIONS_VISA` ADD PRIMARY KEY (`INPUT_FILE_IDENTIFIER`,`INPUT_SEQ_NUMBER`);
ALTER TABLE `CSO_PAYMENT_MCARD_PDS` ADD PRIMARY KEY (`PDS_NUMBER`,`SYSTEM_SEQ_NUMBER`);
ALTER TABLE `CSO_PROGRAM_CONTROLS` ADD PRIMARY KEY (`ARB_DATA`,`PROGRAM_NAME`); 
ALTER TABLE `CSO_SCHEDULE_TIMES` ADD PRIMARY KEY (`PROCESS`,`SERVICE`,`SUB_SERVICE`);
ALTER TABLE `CSO_SCHEDULED_PROCESSES` ADD PRIMARY KEY (`PROCESS_NAME`);
ALTER TABLE `CSO_SEQ_NUMBERS` ADD PRIMARY KEY (`DISTRIBUTION_CODE`,`EXTERNAL_FILENAME_PREFIX`);
ALTER TABLE `CSO_SERVICE_PARAMETERS` ADD PRIMARY KEY (`PROCESS_DATE`,`SERVICE`,`SUB_SERVICE`);
ALTER TABLE `CSO_SYSTEM_CONTROLS` ADD PRIMARY KEY (`PROCESS_DATE`,`SERVICE`,`SUB_SERVICE`,`SYSTEM_FUNCTION`); 
ALTER TABLE `CSO_SYSTEM_PARAMETERS` ADD PRIMARY KEY (`NEXT_OUTPUT_DATE`);
ALTER TABLE `CSO_TRANSACTIONS` ADD PRIMARY KEY (`SYSTEM_SEQ_NUMBER`);
ALTER TABLE `CSO_Z1_Z9_INPUT_OUTPUTS` ADD  PRIMARY KEY (`FILENAME_DESCRIPTION`); 
ALTER TABLE `DEL_DELIVERY_FILES_CCC` ADD PRIMARY KEY (`FILENAME`,`POSITION`,`QUEUE_FILE_NAME`);
ALTER TABLE `SITE_CONTROLS` ADD PRIMARY KEY (`SITE_CODE`);
