ALTER TABLE CCCOWNER.CSO_TRANSACTIONS DROP COLUMN SYSTEM_SEQ_NUMBER;
ALTER TABLE CCCOWNER.CSO_TRANSACTIONS ADD COLUMN SYSTEM_SEQ_NUMBER BIGINT PRIMARY KEY AUTO_INCREMENT;

ALTER TABLE CCCOWNER.CSO_INPUT_FILE_CONTROLS DROP COLUMN SYSTEM_SEQ_NUMBER;
ALTER TABLE CCCOWNER.CSO_INPUT_FILE_CONTROLS ADD COLUMN SYSTEM_SEQ_NUMBER BIGINT PRIMARY KEY AUTO_INCREMENT;

--
-- TODO Move the code below to ORACLE SQL Scripts
--
-- ORACLE SPECIFIC------THIS IS THE SEQUENCE FOR INPUT_FILES_CONTROLS-------------
-- CREATE SEQUENCE CSO_INP_SEQ 
--   START WITH 1 
--   INCREMENT BY 1 
--   MINVALUE 1
--   MAXVALUE 999999;
--
