USE CCCOWNER;
CREATE OR REPLACE VIEW CCCOWNER.CSO_TRANSACTIONS_VIEW
(
	FILE_REF_NUMBER,
    SERVICE,
    SUB_SERVICE,
    ACQUIRER_MEMBER,
    ISSUER_MEMBER,
    CARD_TYPE,
    TRANSACTION_CODE,
    CASHBACK_PRESENT,
    CASHBACK_AMOUNT,
    TRAN_STATUS,
    FILE_STATUS,
    TRAN_AMOUNT,
	ISSUER_BIN,
	ACQUIRER_BIN,
	TRAN_SYSTEM_SEQ_NUMBER,
	BILLING_FEE,
	BILLING_FEE_AMOUNT,
	BILLING_VAT,
	CB_BILL_FEE,
	CB_BILL_FEE_AMNT,
	CB_BILL_VAT,
	FLEET_COUNT_TRAN,
	MESSAGE_TYPE_IND,
	MERCHANT_CAT_CODE,
	INTCHG_RATE_DSGN,
	MESSAGE_REASON_CODE
)
AS
SELECT B.FILE_REF_NUMBER,
	  B.SERVICE,
	  B.SUB_SERVICE,
	  A.ACQUIRER_MEMBER,
	  A.ISSUER_MEMBER,
	  A.CARD_TYPE,
	  CASE
		 WHEN     A.CASHBACK_PRESENT = 'Y'
			  AND A.CASHBACK_AMOUNT < A.TRANSACTION_AMOUNT
		 THEN
			CASE
			   WHEN A.TRANSACTION_CODE BETWEEN 1 AND 9 THEN 3
			   WHEN A.TRANSACTION_CODE BETWEEN 10 AND 19 THEN 13
			   WHEN A.TRANSACTION_CODE BETWEEN 20 AND 29 THEN 23
			END
		 WHEN     A.CASHBACK_PRESENT = 'Y'
			  AND A.CASHBACK_AMOUNT = A.TRANSACTION_AMOUNT
		 THEN
			CASE
			   WHEN A.TRANSACTION_CODE BETWEEN 1 AND 9 THEN 2
			   WHEN A.TRANSACTION_CODE BETWEEN 10 AND 19 THEN 12
			   WHEN A.TRANSACTION_CODE BETWEEN 20 AND 29 THEN 22
			END
		 WHEN A.CASHBACK_PRESENT = 'N'
		 THEN
			A.TRANSACTION_CODE
	  END
		 AS TRANSACTION_CODE,
	  A.CASHBACK_PRESENT,
	  CASE
		 WHEN     A.CASHBACK_PRESENT = 'Y'
			  AND A.CASHBACK_AMOUNT = A.TRANSACTION_AMOUNT
		 THEN
			0
		 ELSE
			A.CASHBACK_AMOUNT
	  END
		 AS CASHBACK_AMOUNT,
	  A.PROCESS_STATUS AS TRAN_STATUS,
	  B.PROCESS_STATUS AS FILE_STATUS,
	  CASE
		 WHEN     A.CASHBACK_PRESENT = 'Y'
			  AND A.CASHBACK_AMOUNT = A.TRANSACTION_AMOUNT
		 THEN
			A.TRANSACTION_AMOUNT
		 ELSE
			A.TRANSACTION_AMOUNT - A.CASHBACK_AMOUNT
	  END
		 AS TRAN_AMOUNT,
	  A.ISSUER_BIN,
	  A.ACQUIRER_BIN,
	  A.SYSTEM_SEQ_NUMBER AS TRAN_SYSTEM_SEQ_NUMBER,
	  A.BILLING_FEE,
	  A.BILLING_FEE_AMOUNT,
	  A.BILLING_VAT,
	  A.CB_BILL_FEE,
	  A.CB_BILL_FEE_AMNT,
	  A.CB_BILL_VAT,
	  A.FLEET_COUNT_TRAN,
	  A.MESSAGE_TYPE_IND,
	  A.MERCHANT_CAT_CODE,
	  A.INTCHG_RATE_DSGN,
	  A.MESSAGE_REASON_CODE
 FROM CSO_TRANSACTIONS A
	  LEFT OUTER JOIN CSO_INPUT_FILE_CONTROLS B
		 ON A.FILE_SYSTEM_SEQ_NUMBER = B.SYSTEM_SEQ_NUMBER;