USE CCCOWNER;
CREATE OR REPLACE VIEW CCCOWNER.CSV_TRANSACTIONS_VIEW
(
   ACQUIRER_MEMBER,
   ACQUIRER_NAME,
   ACQUIRER_BIN,
   ISSUER_MEMBER,
   ISSUER_NAME,
   ISSUER_BIN,
   SERVICE,
   SUB_SERVICE,
   CARD_TYPE,
   CARD_DESCRIPTION,
   TRANSACTION_CODE,
   TRANSACTION_DESCRIPTION,
   TRAN_AMOUNT,
   TRAN_SYSTEM_SEQ_NUMBER,
   CASHBACK_PRESENT,
   CASHBACK_AMOUNT,
   TRAN_STATUS,
   FILE_STATUS,
   MESSAGE_TYPE_IND,
   MERCHANT_CAT_CODE,
   INTCHG_RATE_DSGN,
   MESSAGE_REASON_CODE,
   BILLING_FEE,
   BILLING_FEE_AMOUNT,
   BILLING_VAT,
   CB_BILL_FEE,
   CB_BILL_FEE_AMNT,
   CB_BILL_VAT,
   INTERCHANGE_FEE,
   INTERCHANGE_FEE_AMOUNT,
   INPUT_VAT,
   DEST_REPORT,
   AMOUNT_DIRECTION,
   REPORT_SORT_SEQUENCE,
   CB_INTERCHANGE_FEE,
   CB_INTERHCANGE_FEE_AMOUNT,
   CASHBACK_INPUT_VAT,
   CASHBACK_AMOUNT_DIRECTION,
   FLEET_COUNT_TRAN
)
AS
   SELECT AA.ACQUIRER_MEMBER,
          BB.MEMBER_NAME AS ACQUIRER_NAME,
          AA.ACQUIRER_BIN,
          AA.ISSUER_MEMBER,
          CC.MEMBER_NAME AS ISSUER_NAME,
          AA.ISSUER_BIN,
          AA.SERVICE,
          AA.SUB_SERVICE,
          AA.CARD_TYPE,
          DD.CARD_DESCRIPTION,
          AA.TRANSACTION_CODE,
          EE.TRANSACTION_DESCRIPTION,
          AA.TRAN_AMOUNT,
          AA.TRAN_SYSTEM_SEQ_NUMBER,
          AA.CASHBACK_PRESENT,
          AA.CASHBACK_AMOUNT,
          AA.TRAN_STATUS,
          AA.FILE_STATUS,
          AA.MESSAGE_TYPE_IND,
          AA.MERCHANT_CAT_CODE,
          AA.INTCHG_RATE_DSGN,
          AA.MESSAGE_REASON_CODE,
          AA.BILLING_FEE,
          AA.BILLING_FEE_AMOUNT,
          AA.BILLING_VAT,
          AA.CB_BILL_FEE,
          AA.CB_BILL_FEE_AMNT,
          AA.CB_BILL_VAT,
          FF.INTERCHANGE_FEE,
          FF.INTERCHANGE_FEE_AMOUNT,
          FF.INPUT_VAT,
          FF.DEST_REPORT,
          FF.AMOUNT_DIRECTION,
          EE.REPORT_SORT_SEQUENCE,
          GG.INTERCHANGE_FEE AS CB_INTERCHANGE_FEE,
          GG.INTERCHANGE_FEE_AMOUNT AS CB_INTERHCANGE_FEE_AMOUNT,
          GG.INPUT_VAT AS CASHBACK_INPUT_VAT,
          GG.AMOUNT_DIRECTION AS CASHBACK_AMOUNT_DIRECTION,
          AA.FLEET_COUNT_TRAN
     FROM CSO_TRANSACTIONS_VIEW AA 
          LEFT OUTER JOIN CSF_MEMBERS BB ON AA.ACQUIRER_MEMBER = BB.BANK_CODE
          LEFT OUTER JOIN CSF_MEMBERS CC ON AA.ISSUER_MEMBER = CC.BANK_CODE
          LEFT OUTER JOIN CSF_CARD_TYPES DD ON AA.CARD_TYPE = DD.CARD_TYPE
          LEFT OUTER JOIN CSF_TRANSACTION_TYPES EE
             ON AA.TRANSACTION_CODE = EE.TRANSACTION_CODE
          LEFT OUTER JOIN
          CSF_CARD_FEE_BILATERAL FF
             ON     AA.ISSUER_MEMBER = FF.ISSUING_MEMBER
                AND AA.ACQUIRER_MEMBER = FF.ACQUIRING_MEMBER
                AND AA.CARD_TYPE = FF.CARD_TYPE
                AND AA.TRANSACTION_CODE = FF.TRANSACTION_CODE
          LEFT OUTER JOIN
          CSF_CARD_FEE_BILATERAL GG
             ON     AA.ISSUER_MEMBER = GG.ISSUING_MEMBER
                AND AA.ACQUIRER_MEMBER = GG.ACQUIRING_MEMBER
                AND AA.CARD_TYPE = GG.CARD_TYPE
                AND GG.TRANSACTION_CODE =
                       (CASE
                           WHEN AA.TRANSACTION_CODE BETWEEN 0 AND 9 THEN 8
                           WHEN AA.TRANSACTION_CODE BETWEEN 10 AND 19 THEN 18
                           WHEN AA.TRANSACTION_CODE BETWEEN 20 AND 29 THEN 28
                        END);

