DROP TABLE IF EXISTS CCCOWNER.DMCS_SEQ_STORE;
CREATE TABLE CCCOWNER.DMCS_SEQ_STORE
(
  DMCS_SEQ_NAME VARCHAR(255) NOT NULL,
  DMCS_SEQ_VALUE BIGINT NOT NULL,
  PRIMARY KEY (DMCS_SEQ_NAME)
);
INSERT INTO CCCOWNER.DMCS_SEQ_STORE(DMCS_SEQ_NAME, DMCS_SEQ_VALUE)
VALUES('TRANSACTIONS.SYSTEM_SEQ_NUMBER',
 (SELECT IFNULL(MAX(SYSTEM_SEQ_NUMBER)+1, 1) FROM CCCOWNER.CSO_TRANSACTIONS));
INSERT INTO CCCOWNER.DMCS_SEQ_STORE(DMCS_SEQ_NAME, DMCS_SEQ_VALUE)
VALUES('IN_FILE_CONT.SYSTEM_SEQ_NUMBER',
 (SELECT IFNULL(MAX(SYSTEM_SEQ_NUMBER)+1, 1) FROM CCCOWNER.CSO_INPUT_FILE_CONTROLS));
