USE CCCOWNER;
CREATE OR REPLACE VIEW CCCOWNER.CCR00X_REPORT_LAYOUT_VIEW
(
    ISSUER_MEMBER,
    ISSUER_CODE,
    ACQUIRER_MEMBER,
    ACQUIRER_CODE,
    SUB_SERVICE,
    DISPLAY_NAME,
    CARD_TYPE,
    CARD_DESCRIPTION,
    TRANSACTION_CODE,
    TRANSACTION_DESCRIPTION,
    REPORT_SORT_SEQUENCE,
    SERVICE
)
 AS
    SELECT A.MEMBER_NAME AS ISSUER_MEMBER,
           A.BANK_CODE AS ISSUER_CODE,
           B.MEMBER_NAME AS ACQUIRER_MEMBER,
           B.BANK_CODE AS ACQUIRER_CODE,
           C.SUB_SERVICE,
           C.DISPLAY_NAME,
           F.CARD_TYPE,
           F.CARD_DESCRIPTION,
           G.TRANSACTION_CODE,
           G.TRANSACTION_DESCRIPTION,
           G.REPORT_SORT_SEQUENCE,
           C.SERVICE
      FROM CSF_MEMBERS A,
           CSF_MEMBERS B,
           CSF_SUB_SERVICES C,
           CSF_MEMBER_SERVICE D,
           CSF_MEMBER_SERVICE E,
           CSF_CARD_TYPES F,
           CSF_TRANSACTION_TYPES_COLLATED_VIEW G
     WHERE     A.MNEMONIC_MEMBER_NAME IS NOT NULL
           AND B.MNEMONIC_MEMBER_NAME IS NOT NULL
           AND A.BANK_CODE <> B.BANK_CODE
           AND A.BANK_CODE = D.BANK_CODE
           AND B.BANK_CODE = E.BANK_CODE
           AND C.SUB_SERVICE = D.SUB_SERVICE
           AND D.SUB_SERVICE = E.SUB_SERVICE
           AND D.SUB_SERVICE = F.SUB_SERVICE
           AND C.SERVICE = D.SERVICE
           AND D.SERVICE = E.SERVICE