USE CCCOWNER;
CREATE OR REPLACE VIEW CCCOWNER.CCR00X_REPORT_DATA_VIEW
(
    ACQUIRER_MEMBER,
    ISSUER_MEMBER,
    SERVICE,
    CARD_TYPE,
    TRANSACTION_CODE,
    DEST_REPORT,
    VOLUME,
    TRAN_VALUE,
    BILLING_FEE,
    BILLING_FEE_AMOUNT,
    BILLING_VAT
)
  AS
      SELECT ACQUIRER_MEMBER,
               ISSUER_MEMBER,
               SERVICE,
               CARD_TYPE,
               TRANSACTION_CODE,
               DEST_REPORT,
               SUM(VOLUME) AS VOLUME,
               ROUND (SUM(TRAN_VALUE), 2) * AMOUNT_DIRECTION
                  AS TRAN_VALUE,
               ROUND (SUM(BILLING_FEE), 2) AS BILLING_FEE,
               ROUND (SUM(BILLING_FEE_AMOUNT), 2) AS BILLING_FEE_AMOUNT,
               ROUND (SUM(BILLING_VAT), 2) AS BILLING_VAT
          FROM CSV_TRANSACTIONS_VIEW_COLLATED
      GROUP BY ACQUIRER_MEMBER,
               ISSUER_MEMBER,
               SERVICE,
               CARD_TYPE,
               TRANSACTION_CODE,
               DEST_REPORT,
               AMOUNT_DIRECTION