USE CCCOWNER;
CREATE OR REPLACE VIEW CCCOWNER.CSV_CCR00X_DATA_VIEW
(
   ISSUER_MEMBER,
   ISSUER_CODE,
   ACQUIRER_MEMBER,
   ACQUIRER_CODE,
   SERVICE,
   SUB_SERVICE,
   CARD_TYPE,
   CARD_DESCRIPTION,
   TRANSACTION_CODE,
   TRANSACTION_DESCRIPTION,
   VOLUME,
   TRAN_VALUE,
   BILLING_FEE,
   BILLING_FEE_AMOUNT,
   BILLING_VAT,
   REPORT_SORT_SEQUENCE
)
AS
     SELECT AAA.ISSUER_MEMBER,
            AAA.ISSUER_CODE,
            AAA.ACQUIRER_MEMBER,
            AAA.ACQUIRER_CODE,
            AAA.SERVICE,
            AAA.SUB_SERVICE,
            AAA.CARD_TYPE,
            AAA.CARD_DESCRIPTION,
            AAA.TRANSACTION_CODE,
            AAA.TRANSACTION_DESCRIPTION,
            IFNULL (BBB.VOLUME, 0) AS VOLUME,
            IFNULL (BBB.TRAN_VALUE, 0) AS TRAN_VALUE,
            IFNULL (BBB.BILLING_FEE, 0) AS BILLING_FEE,
            IFNULL (BBB.BILLING_FEE_AMOUNT, 0) AS BILLING_FEE_AMOUNT,
            IFNULL (BBB.BILLING_VAT, 0) AS BILLING_VAT,
            AAA.REPORT_SORT_SEQUENCE
       FROM CCR00X_REPORT_LAYOUT_VIEW AAA
            LEFT OUTER JOIN
            CCR00X_REPORT_DATA_VIEW BBB
               ON     AAA.ISSUER_CODE = BBB.ISSUER_MEMBER
                  AND AAA.ACQUIRER_CODE = BBB.ACQUIRER_MEMBER
                  AND AAA.SERVICE = BBB.SERVICE
                  AND AAA.CARD_TYPE = BBB.CARD_TYPE
                  AND AAA.TRANSACTION_CODE = BBB.TRANSACTION_CODE
   ORDER BY AAA.ISSUER_CODE,
            AAA.ACQUIRER_CODE,
            AAA.SERVICE,
            AAA.SUB_SERVICE,
            AAA.CARD_TYPE,
            AAA.REPORT_SORT_SEQUENCE;

-- ALTER VIEW CCCOWNER.CSV_CCR00X_DATA_VIEW
-- ADD CONSTRAINT CCR000XDATAVIEW_PK
--  PRIMARY KEY
--  (ISSUER_CODE, ACQUIRER_CODE, CARD_TYPE, TRANSACTION_CODE)
--  DISABLE;
