USE CCCOWNER;
DROP TABLE IF EXISTS  `CSS_MONTH_STATS`;
CREATE TABLE `CSS_MONTH_STATS` (
  `PROCESS_DATE` DATE NOT NULL,
  `ISSUER_BIN` VARCHAR(6) NOT NULL,
  `ACQUIRER_BIN` VARCHAR(6) NOT NULL,
  `SERVICE` VARCHAR(4) NOT NULL,
  `SUB_SERVICE` VARCHAR(10) NOT NULL,
  `TRANSACTION_CODE` VARCHAR(2) NOT NULL,
  `PROCESS_STATUS` VARCHAR(1) NOT NULL,
  `CARD_TYPE` VARCHAR(2) NOT NULL,
  `SETTLE_DATE` DATE NOT NULL,
  `TRANSACTION_DATE` DATE DEFAULT NULL,
  `FINANCIAL_IND` VARCHAR(1) DEFAULT NULL,
  `MESSAGE_TYPE_IND` INT(11) DEFAULT NULL,
  `PROCESS_CODE` INT(11) DEFAULT NULL,
  `RECORD_ID` INT(11) DEFAULT NULL,
  `REVERSAL_IND` VARCHAR(1) DEFAULT NULL,
  `MERCHANT_CAT_CODE` VARCHAR(4) NOT NULL,
  `INTCHG_RATE_DSGN` INT(11) DEFAULT NULL,
  `MESSAGE_REASON_CODE` INT(11) DEFAULT NULL,
  `TOTAL_AMOUNT` DECIMAL(16,2) DEFAULT NULL,
  `TOTAL_COUNT` DECIMAL(8,0) DEFAULT NULL,
  `BILLING_AMOUNT` DECIMAL(15,5) DEFAULT '0.00000',
  `BILLING_PERC_AMOUNT` DECIMAL(15,5) DEFAULT '0.00000',
  `BILLING_VAT` DECIMAL(15,5) DEFAULT '0.00000',
  `ACQUIRER_MEMBER` INT(11) DEFAULT '0',
  `ISSUER_MEMBER` INT(11) DEFAULT '0'
);