USE CCCOWNER;
CREATE OR REPLACE VIEW CCCOWNER.CSS_STATS_VIEW
(
    PROCESS_MONTH,
    ISSUER_BIN,
    ISSUING_MEMBER,
    ISSUING_MEMBER_NAME,
    ACQUIRER_BIN,
    ACQUIRING_MEMBER,
    ACQUIRING_MEMBER_NAME,
    SERVICE,
    SUB_SERVICE,
    TRANSACTION_CODE,
    TRANSACTION_DESCRIPTION,
    CARD_TYPE,
    CARD_DESCRIPTION,
    PROCESS_STATUS,
    MERCHANT_CAT_CODE,
    INTERCHANGE_RATE_DESIGNATOR,
    ITEM_CHARGE,
    ITEM_CHARGE_AMOUNT,
    VAT,
    TOTAL_COUNT,
    TOTAL_AMOUNT,
    TOTAL_COST,
    TOTAL_VAT
  ) AS
      SELECT DATE_FORMAT (A.PROCESS_DATE, '%Y%M') AS PROCESS_MONTH,
            A.ISSUER_BIN,
            A.ISSUER_MEMBER,
            D.MEMBER_NAME AS ISSUER_MEMBER_NAME,
            A.ACQUIRER_BIN,
            A.ACQUIRER_MEMBER,
            F.MEMBER_NAME AS ACQUIRER_MEM_NAME,
            A.SERVICE,
            A.SUB_SERVICE,
            A.TRANSACTION_CODE,
            G.TRANSACTION_DESCRIPTION,
            A.CARD_TYPE,
            H.CARD_DESCRIPTION,
            A.PROCESS_STATUS,
            A.MERCHANT_CAT_CODE,
            A.INTCHG_RATE_DSGN,
            ABS(I.INTERCHANGE_FEE),
            ABS(I.INTERCHANGE_FEE_AMOUNT),
            ABS(I.INPUT_VAT),
            ABS(SUM(A.TOTAL_COUNT)) AS TOTAL_COUNT,
            ABS(SUM(A.TOTAL_AMOUNT)) AS TOTAL_AMOUNT,
            ABS(SUM(A.BILLING_AMOUNT + A.BILLING_PERC_AMOUNT)) AS TOTAL_COST,
            ABS(SUM(A.BILLING_VAT)) AS VAT
       FROM CSS_MONTH_STATS A
            LEFT OUTER JOIN CSF_MEMBERS D
               ON A.ISSUER_MEMBER = D.BANK_CODE
            LEFT OUTER JOIN CSF_MEMBERS F
               ON A.ACQUIRER_MEMBER = F.BANK_CODE
            LEFT OUTER JOIN CSF_TRANSACTION_TYPES G
               ON CAST(A.TRANSACTION_CODE AS SIGNED INTEGER) =
                     CAST(G.TRANSACTION_CODE AS SIGNED INTEGER)
            LEFT OUTER JOIN CSF_CARD_TYPES H
               ON CAST(A.CARD_TYPE AS SIGNED INTEGER) = CAST(H.CARD_TYPE AS SIGNED INTEGER)
            LEFT OUTER JOIN CSF_CARD_FEE_BILATERAL I
               ON     A.ISSUER_MEMBER = I.ISSUING_MEMBER
                  AND A.ACQUIRER_MEMBER = I.ACQUIRING_MEMBER
                  AND CAST(A.CARD_TYPE AS SIGNED INTEGER) = CAST(I.CARD_TYPE AS SIGNED INTEGER)
                  AND CAST(A.TRANSACTION_CODE AS SIGNED INTEGER) =
                        CAST(I.TRANSACTION_CODE AS SIGNED INTEGER)
      WHERE A.ACQUIRER_MEMBER <> 0 AND A.ISSUER_MEMBER <> 0
   GROUP BY DATE_FORMAT(A.PROCESS_DATE, '%Y%M'),
            A.ISSUER_BIN,
            A.ISSUER_MEMBER,
            D.MEMBER_NAME,
            A.ACQUIRER_BIN,
            A.ACQUIRER_MEMBER,
            F.MEMBER_NAME,
            A.SERVICE,
            A.SUB_SERVICE,
            A.TRANSACTION_CODE,
            G.TRANSACTION_DESCRIPTION,
            A.CARD_TYPE,
            H.CARD_DESCRIPTION,
            A.PROCESS_STATUS,
            A.MERCHANT_CAT_CODE,
            A.INTCHG_RATE_DSGN,
            I.INTERCHANGE_FEE,
            I.INTERCHANGE_FEE_AMOUNT,
            I.INPUT_VAT;