
-- Write Headers -------------------------------------------------------------------------------------------------------

-- Check duplicate CSO_INPUT_FILE_CONTROLS using file_reference_number, if PROCESS_STATUS = F, delete and proceed

--  Write CSO_INPUT_FILE_CONTROLS record

-- Header record type 01, AXSHeader, filter : POSITION (0, 2) = '01'

LOAD DATA
APPEND
INTO TABLE CSO_INPUT_FILE_CONTROLS
WHEN (01:02) = '01'
   (
      FILE_REF_NUMBER POSITION (03:32), -- VARCHAR2(60 BYTE) NOT NULL
      OUTPUT_DATE     POSITION (11:19) DATE 'YYYYMMDD', -- CONSTANT '17-NOV-16', -- POSITION (03:10) DATE 'YYYYMMDD', -- CONSTANT '17-NOV-16', --POSITION (03:10) DATE,
      SERVICE         POSITION (33:36),
      SUB_SERVICE     POSITION (37:40),
      NUMBER_OF_RECS  POSITION (61:71),
      NUMBER_DEBITS   POSITION (72:82),
      NUMBER_CREDITS  POSITION (83:93),
      CREDIT_VALUE    POSITION (94:104),
      DEBIT_VALUE     POSITION (105:115),
      -- HASH_TOTAL      -- NUMBER(12, 0)
      -- LAST_FILE_INDICATOR  -- VARCHAR2(1 BYTE)
      PROCESS_STATUS  POSITION (116 : 116),     -- VARCHAR2(1 BYTE)
      -- EXTRACTED_COUNT      -- NUMBER(6, 0)
      -- EXT_CREDITS          NUMBER(6, 0)
      -- EXT_DEBITS NUMBER(6, 0)
      -- EXT_CREDIT_VALUE NUMBER(16, 2)
      -- EXT_DEBIT_VALUE NUMBER(16, 2)
      -- LAST_PROCESS_DATE DATE
      -- NEXT_OUTPUT_DATE DATE
      -- SETTLEMENT_COUNT NUMBER(6, 0)
      -- LOAD_DATE DATE
      ORIGINATING_MEMBER POSITION (47:50), -- NUMBER(4, 0)
      -- validation_code position(28, 32),
      -- NEGATIVE_CARD_COUNT NUMBER(6, 0)
      -- NEGATIVE_DUPLICATE_COUNT NUMBER(6, 0)
      -- LAST_COMMITED_RECORD_POINTER NUMBER(8, 0)
      -- EXCEP_REP_PRODUCED_IND VARCHAR2(1 BYTE)
      -- ERROR_FILENAME VARCHAR2(6 BYTE)
      SYSTEM_SEQ_NUMBER POSITION  (51 : 60), --NUMBER(10, 0) NOT NULL
      ODS_DATA_STATUS   CONSTANT '1',
      IS_BILLED         CONSTANT 'N',
      IS_PRE_EXTRACTED  CONSTANT 'Y'
   )
INTO TABLE CSO_TRANSACTIONS
WHEN (01:02) <> '-1' AND (01:02) <> '01' AND (01:02) <> '92' AND (01:02) <> '98' AND (01:02) <> '99' AND (03:04) = '00'
  (
    FILE_SYSTEM_SEQ_NUMBER POSITION (169 : 178),
    SYSTEM_SEQ_NUMBER      POSITION (179 : 189),
    TRANSACTION_CODE       POSITION ( 01 :  02),
    CARD_TYPE              POSITION (220 : 221),
    ACQUIRER_MEMBER        POSITION (214 : 219),
    ISSUER_MEMBER          POSITION (220 : 225),
    ISSUER_BIN             POSITION (5   : 10),
    ACCOUNT_NUMBER         POSITION (5   : 20),
    ACQUIRER_BIN           POSITION (28  : 33),
    PROCESS_STATUS         POSITION (240 : 240),
    TRANSACTION_AMOUNT     POSITION (77  : 88), -- INTEGER "DECODE(:TRANSACTION_AMOUNT, NULL, -1, :TRANSACTION_AMOUNT)", -- REGEXP_LIKE(:TRANSACTION_AMOUNT, '^\\d+(\\.\\d+)?$', '-1'),
    CASHBACK_PRESENT       CONSTANT 'N', --- ???
    CASHBACK_AMOUNT        CONSTANT '0', --- ???
    OUTPUT_FILENAME        POSITION (232 : 239),
    BILLING_FEE            POSITION (240 : 250),
    BILLING_FEE_AMOUNT     POSITION (251 : 261),
    BILLING_VAT            POSITION (262 : 273),
    CB_BILL_FEE            POSITION (274 : 284),
    CB_BILL_FEE_AMNT       POSITION (285 : 295),
    CB_BILL_VAT            POSITION (296 : 306),
    EXTRACTIND             CONSTANT 'N',
    RECORD_NUMBER          POSITION (222 : 231),
    RECORD_START_BYTE      CONSTANT '0',
    RECORD_END_BYTE        CONSTANT '0',
    FILE_RECORD_CNT        CONSTANT '0',
    FLEET_COUNT_TRAN       CONSTANT '0',
    OPFILE_NUM_SEQ         CONSTANT '0'
    -- FILE_RECORD_CNT NUMBER(3, 0) DEFAULT 1  --- calculated

 )

 INTO TABLE CSO_PAYMENT_INSTRUCTIONS_VISA
 WHEN (01:02) <> '-1' AND (01:02) <> '01' AND (01:02) <> '92' AND (01:02) <> '98' AND (01:02) <> '99' AND (03:04) = '00'
    (
      FILE_REF_NUMBER         POSITION (169 : 178),
      SYSTEM_GEN_SEQ_NUMBER   POSITION (179 : 189),
      INPUT_SEQ_NUMBER        POSITION (198 : 207),
      INPUT_FILE_IDENTIFIER   CONSTANT 'I',
      TRANSACTION_CODE        POSITION ( 01 :  02),
      TRANSACTION_CODE_NUMBER POSITION ( 03 :  04),
      ACCOUNT_NUMBER         POSITION( 5 : 20),
      SERVICE                 POSITION (190 : 193),
      SUB_SERVICE             POSITION (194 : 197),
      CARD_TRANSACTION        POSITION ( 01 : 168),
      CARD_TYPE               POSITION (220 : 221),
      ACQUIRER_MEMBER         POSITION (214 : 219),
      ISSUER_MEMBER           POSITION (220 : 225),
      VISA_AMOUNT             POSITION (77 : 88), 
      FILENAME_DESCRIPTION    POSITION (232 : 239),
      POS_ENTRY_MODE          POSITION (307 : 308),
      TERMINAL_CAPABILITY     POSITION (309 : 309),
      CHIP_CARD               POSITION (310 : 310),
      ECOMM_IND               POSITION (311 : 311),
      CARD_PRESENT            POSITION (312 : 312),
      CASHBACK_PURCHASE_AMNT  POSITION (313 : 322),
      CASHBACK_PURCHASE       POSITION (323 : 323),
      PROCESS_STATUS          POSITION (324 : 324),
      FINANCIAL_INDICATOR     CONSTANT 'Y'
 )
 INTO TABLE CSO_PAYMENT_INSTRUCTIONS_VISA
 WHEN (01:02) <> '-1' AND (01:02) <> '01'  AND (01:02) <> '92' AND (01:02) <> '98' AND (01:02) <> '99' AND (03:04) = '01'
    (
      FILE_REF_NUMBER         POSITION (169 : 178),
      SYSTEM_GEN_SEQ_NUMBER   POSITION (179 : 189),
      INPUT_SEQ_NUMBER        POSITION (198 : 207),
      INPUT_FILE_IDENTIFIER   CONSTANT 'I',
      TRANSACTION_CODE        POSITION ( 01 :  02),
      TRANSACTION_CODE_NUMBER POSITION ( 03 :  04),
      SERVICE                 POSITION (190 : 193),
      SUB_SERVICE             POSITION (194 : 197),
      CARD_TRANSACTION        POSITION ( 01 : 168),
      FILENAME_DESCRIPTION    POSITION (232 : 239),
      PROCESS_STATUS          POSITION (324 : 324),
      FINANCIAL_INDICATOR     CONSTANT 'N'
 )
 INTO TABLE CSO_PAYMENT_INSTRUCTIONS_VISA
 WHEN (01:02) <> '-1' AND (01:02) <> '01'  AND (01:02) <> '92' AND (01:02) <> '98' AND (01:02) <> '99' AND (03:04) = '05'
    (
      FILE_REF_NUMBER         POSITION (169 : 178),
      SYSTEM_GEN_SEQ_NUMBER   POSITION (179 : 189),
      INPUT_SEQ_NUMBER        POSITION (198 : 207),
      INPUT_FILE_IDENTIFIER   CONSTANT 'I',
      TRANSACTION_CODE        POSITION ( 01 :  02),
      TRANSACTION_CODE_NUMBER CONSTANT '5',
      SERVICE                 POSITION (190 : 193),
      SUB_SERVICE             POSITION (194 : 197),
      CARD_TRANSACTION        POSITION ( 01 : 168),
      FILENAME_DESCRIPTION    POSITION (232 : 239),
      PROCESS_STATUS          POSITION (324 : 324),
      FINANCIAL_INDICATOR     CONSTANT 'N'
 )
 INTO TABLE CSO_PAYMENT_INSTRUCTIONS_VISA
 WHEN (01:02) <> '-1' AND (01:02) <> '01' AND (01:02) <> '92' AND (01:02) <> '98' AND (01:02) <> '99' AND (03:04) = '07'
    (
      FILE_REF_NUMBER         POSITION (169 : 178),
      SYSTEM_GEN_SEQ_NUMBER   POSITION (179 : 189),
      INPUT_SEQ_NUMBER        POSITION (198 : 207),
      INPUT_FILE_IDENTIFIER   CONSTANT 'I',
      TRANSACTION_CODE        POSITION ( 01 :  02),
      TRANSACTION_CODE_NUMBER CONSTANT '7',
      SERVICE                 POSITION (190 : 193),
      SUB_SERVICE             POSITION (194 : 197),
      CARD_TRANSACTION        POSITION ( 01 : 168),
      FILENAME_DESCRIPTION    POSITION (232 : 239),
      PROCESS_STATUS          POSITION (324 : 324),
      FINANCIAL_INDICATOR     CONSTANT 'N'
 )
-- Write Transactions --------------------------------------------------------------------------------------------------
