BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE DMCS_SEQ_STORE';
    EXCEPTION WHEN OTHERS THEN NULL;
    
    EXECUTE IMMEDIATE '
       CREATE TABLE CCCOWNER.DMCS_SEQ_STORE
       (
          DMCS_SEQ_NAME VARCHAR2(30) NOT NULL,
          DMCS_SEQ_VALUE NUMBER(19) NOT NULL,
         PRIMARY KEY (DMCS_SEQ_NAME)
       )
    ';

    EXECUTE IMMEDIATE '
       INSERT INTO CCCOWNER.DMCS_SEQ_STORE(DMCS_SEQ_NAME, DMCS_SEQ_VALUE)
       VALUES(''TRANSACTIONS.SYSTEM_SEQ_NUMBER'',
               ( SELECT NVL(MAX(SYSTEM_SEQ_NUMBER)+1, 1) 
                   FROM CCCOWNER.CSO_TRANSACTIONS
               )
             )
    ';

    EXECUTE IMMEDIATE '
       INSERT INTO CCCOWNER.DMCS_SEQ_STORE(DMCS_SEQ_NAME, DMCS_SEQ_VALUE)
       VALUES(''IN_FILE_CONT.SYSTEM_SEQ_NUMBER'',
               ( SELECT NVL(MAX(SYSTEM_SEQ_NUMBER)+1, 1) 
                   FROM CCCOWNER.CSO_INPUT_FILE_CONTROLS
               )
             )
    ';
END;